import assert from "node:assert/strict";
import test from "node:test";
import { CLASSIFICATION_HIGH_IMPORTANCE, CLASSIFICATION_IMPORTANT_UNCERTAIN_CONFIDENCE, CLASSIFICATION_LOW_CONFIDENCE, MORNING_BRIEF_MODELS, assertMorningBriefGenerativeModel, classificationEscalationReason, classificationModelRoute, resolveMorningBriefModels, shouldEscalateClassification } from "./ai-models";

test("Morning Brief defaults are Luna, Terra, and text-embedding-3-small", () => { const models = resolveMorningBriefModels({}); assert.equal(models.default, "gpt-5.6-luna"); assert.equal(models.advanced, "gpt-5.6-terra"); assert.equal(models.embedding, "text-embedding-3-small"); assert.equal(MORNING_BRIEF_MODELS.default, "gpt-5.6-luna"); });
test("hard allowlist rejects Sol, generic aliases, and unknown models", () => { assert.equal(assertMorningBriefGenerativeModel("gpt-5.6-luna"), "gpt-5.6-luna"); assert.equal(assertMorningBriefGenerativeModel("gpt-5.6-terra"), "gpt-5.6-terra"); for (const model of ["gpt-5.6-sol", "gpt-5.6", "unknown"]) assert.throws(() => assertMorningBriefGenerativeModel(model)); assert.throws(() => resolveMorningBriefModels({ MORNING_BRIEF_LUNA_MODEL: "gpt-5.6-sol" })); });
test("normal Luna confidence 72 stays Luna while low confidence 55 escalates", () => { assert.equal(classificationEscalationReason({ confidence: 72 }), null); assert.equal(classificationEscalationReason({ confidence: 55 }), "low_confidence"); assert.equal(shouldEscalateClassification(CLASSIFICATION_LOW_CONFIDENCE), false); assert.equal(shouldEscalateClassification(CLASSIFICATION_LOW_CONFIDENCE - 1), true); });
test("important uncertain Luna classification is Terra-eligible", () => { assert.equal(classificationEscalationReason({ confidence: 65, significance: CLASSIFICATION_HIGH_IMPORTANCE, consequence: 10, scope: 10 }), "important_uncertain"); assert.equal(classificationEscalationReason({ confidence: CLASSIFICATION_IMPORTANT_UNCERTAIN_CONFIDENCE, significance: CLASSIFICATION_HIGH_IMPORTANCE }), null); assert.equal(classificationEscalationReason({ confidence: 85, significance: 100 }), null); });
test("invalid structured output is Terra-eligible and Terra is final without Sol", () => { assert.equal(classificationEscalationReason({ confidence: 90, invalidStructure: true }), "invalid_structure"); assert.deepEqual(classificationModelRoute({ confidence: 55 }), ["gpt-5.6-luna", "gpt-5.6-terra"]); assert.deepEqual(classificationModelRoute({ confidence: 72 }), ["gpt-5.6-luna"]); assert.equal(classificationModelRoute({ confidence: 55 }).includes("gpt-5.6-sol" as never), false); });
