export type ExtractedArticle = { canonicalUrl: string; title: string; excerpt: string; author?: string; publishedAt?: string; language?: string; imageUrl?: string; imageAlt?: string; siteName: string; text: string; contentAvailability: "full_public_text" | "partial_text" | "metadata_only" };
const entity = (value: string) => value.replace(/&amp;/g, "&").replace(/&quot;/g, '"').replace(/&#39;|&apos;/g, "'").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/\s+/g, " ").trim();
const attr = (html: string, key: string) => { const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); const patterns = [new RegExp(`<meta[^>]+(?:property|name)=["']${escaped}["'][^>]+content=["']([^"']*)`, "i"), new RegExp(`<meta[^>]+content=["']([^"']*)["'][^>]+(?:property|name)=["']${escaped}["']`, "i")]; return patterns.map((pattern) => html.match(pattern)?.[1]).find(Boolean); };
const link = (html: string, rel: string) => html.match(new RegExp(`<link[^>]+rel=["'][^"']*${rel}[^"']*["'][^>]+href=["']([^"']+)`, "i"))?.[1];
export function extractArticleHtml(html: string, fetchedUrl: string): ExtractedArticle {
  const scripts = [...html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)]; let json: Record<string, unknown> = {};
  for (const match of scripts) try { const value = JSON.parse(match[1] ?? ""); const candidates = Array.isArray(value) ? value : value?.['@graph'] ?? [value]; const article = (Array.isArray(candidates) ? candidates : [candidates]).find((item) => typeof item === "object" && item && /Article|NewsArticle|BlogPosting/.test(String((item as Record<string, unknown>)['@type']))); if (article) { json = article as Record<string, unknown>; break; } } catch { /* malformed public metadata is ignored */ }
  const title = entity(String(json.headline ?? attr(html, "og:title") ?? html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1] ?? "")); const excerpt = entity(String(json.description ?? attr(html, "description") ?? attr(html, "og:description") ?? "")); if (!title) throw new Error("Unable to extract article metadata.");
  const cleaned = html.replace(/<(script|style|nav|footer|header|aside|form)[^>]*>[\s\S]*?<\/\1>/gi, " "); const paragraphs = [...cleaned.matchAll(/<p[^>]*>([\s\S]*?)<\/p>/gi)].map((match) => entity((match[1] ?? "").replace(/<[^>]+>/g, " "))).filter((text) => text.length >= 40); const text = paragraphs.join("\n\n").slice(0, 30_000);
  const siteName = entity(String(json.publisher && typeof json.publisher === "object" ? (json.publisher as Record<string, unknown>).name ?? "" : attr(html, "og:site_name") ?? new URL(fetchedUrl).hostname)); const canonicalRaw = link(html, "canonical") ?? fetchedUrl;
  return { canonicalUrl: new URL(canonicalRaw, fetchedUrl).toString(), title, excerpt, author: typeof json.author === "object" && json.author ? String((Array.isArray(json.author) ? json.author[0] : json.author as Record<string, unknown>)?.name ?? "") || undefined : undefined, publishedAt: String(json.datePublished ?? attr(html, "article:published_time") ?? "") || undefined, language: html.match(/<html[^>]+lang=["']([^"']+)/i)?.[1], imageUrl: String(json.image && typeof json.image === "string" ? json.image : attr(html, "og:image") ?? "") || undefined, imageAlt: attr(html, "og:image:alt"), siteName, text, contentAvailability: text.length > 2_000 ? "full_public_text" : text.length > 200 ? "partial_text" : "metadata_only" };
}
