import "server-only";
import { createServiceSupabaseClient } from "@/lib/supabase/service";
import { EMBEDDING_DIMENSIONS, EMBEDDING_MODEL, EMBEDDING_VERSION, buildEmbeddingInput, embeddingInputHash, needsEmbeddingGeneration, parseVector } from "./embedding-contract";
export { EMBEDDING_DIMENSIONS, EMBEDDING_MODEL, EMBEDDING_VERSION, buildEmbeddingInput, embeddingInputHash, needsEmbeddingGeneration, parseVector } from "./embedding-contract";
const vectorLiteral = (vector: number[]) => `[${vector.join(",")}]`;
export async function generateEmbeddings(inputs: string[]) { const apiKey = process.env.OPENAI_API_KEY; if (!apiKey) throw new Error("OPENAI_API_KEY is not configured."); const response = await fetch("https://api.openai.com/v1/embeddings", { method: "POST", headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: EMBEDDING_MODEL, dimensions: EMBEDDING_DIMENSIONS, input: inputs }) }); if (!response.ok) throw new Error(`Embedding provider unavailable (${response.status}).`); const body = await response.json() as { data?: Array<{ index: number; embedding: number[] }> }; const ordered = [...(body.data ?? [])].sort((a, b) => a.index - b.index).map((item) => item.embedding); if (ordered.length !== inputs.length || ordered.some((vector) => vector.length !== EMBEDDING_DIMENSIONS || vector.some((value) => !Number.isFinite(value)))) throw new Error("Embedding provider returned an invalid vector."); return ordered; }
export async function ensureArticleEmbeddings(articleIds: string[]) {
  const db = createServiceSupabaseClient(); const ids = [...new Set(articleIds)].filter(Boolean); if (!ids.length) return new Map<string, number[]>();
  const [{ data: articles }, { data: classifications }] = await Promise.all([db.from("morning_brief_articles").select("id,title,excerpt,body_text,content_type").in("id", ids), db.from("morning_brief_article_classifications").select("article_id,countries,regions,categories,topics,sectors,companies,event_type,summary,created_at").in("article_id", ids).order("created_at", { ascending: false })]);
  const latest = new Map<string, NonNullable<typeof classifications>[number]>(); for (const row of classifications ?? []) if (!latest.has(row.article_id)) latest.set(row.article_id, row);
  const candidates = (articles ?? []).flatMap((article) => { const classification = latest.get(article.id); if (!classification) return []; const input = buildEmbeddingInput({ ...article, ...classification }); return [{ articleId: article.id, input, hash: embeddingInputHash(input) }]; });
  const { data: existing } = await db.from("morning_brief_article_embeddings").select("article_id,embedding,input_hash").in("article_id", candidates.map((candidate) => candidate.articleId)).eq("embedding_model", EMBEDDING_MODEL).eq("embedding_version", EMBEDDING_VERSION);
  const vectors = new Map<string, number[]>(); const missing = candidates.filter((candidate) => { const found = (existing ?? []).find((row) => row.article_id === candidate.articleId && !needsEmbeddingGeneration(row.input_hash, candidate.hash)); const vector = found ? parseVector(found.embedding) : null; if (vector) vectors.set(candidate.articleId, vector); return !vector; });
  if (!missing.length) return vectors;
  try { const generated = await generateEmbeddings(missing.map((candidate) => candidate.input)); const rows = missing.map((candidate, index) => ({ article_id: candidate.articleId, embedding: vectorLiteral(generated[index]!), embedding_model: EMBEDDING_MODEL, embedding_version: EMBEDDING_VERSION, input_hash: candidate.hash })); const { error } = await db.from("morning_brief_article_embeddings").upsert(rows, { onConflict: "article_id,embedding_model,embedding_version,input_hash" }); if (error) throw error; missing.forEach((candidate, index) => vectors.set(candidate.articleId, generated[index]!)); } catch (error) { console.error("[morning-brief] embedding generation failed", { name: error instanceof Error ? error.name : "Error", message: error instanceof Error ? error.message : "Unknown error", articleCount: missing.length }); }
  return vectors;
}
