import assert from "node:assert/strict";
import test from "node:test";
import { canRecordStoryOpen, deriveCurrentState, deriveLibraryStoryIds, effectiveAffinity, extractPreferenceSignals, applyFeedback, helsinkiDateKey, learnedPreference, updateLearnedProfile } from "./learning.ts";
import { createLearningDemo } from "./learning-demo.ts";
import { RANKING_WEIGHTS } from "./ranking.ts";
import { MOCK_CORPUS_NOW, MOCK_NEWS_CORPUS } from "./mock-corpus.ts";
const article = MOCK_NEWS_CORPUS.find((item) => item.id === "vietnam-bank-credit")!;
test("append-only events resolve heart, save and negative state", () => { assert.deepEqual(deriveCurrentState([{ eventType: "like", storyId: "a", createdAt: "2026-01-01" }, { eventType: "unlike", storyId: "a", createdAt: "2026-01-02" }, { eventType: "like", storyId: "a", createdAt: "2026-01-03" }, { eventType: "save", storyId: "a", createdAt: "2026-01-01" }, { eventType: "unsave", storyId: "a", createdAt: "2026-01-02" }, { eventType: "not_relevant", storyId: "a", createdAt: "2026-01-04" }]), { liked: true, saved: false, notRelevant: true, fewerLikeThis: false }); });
test("learning is bounded, topic-led and decays toward neutral", () => { const signals = extractPreferenceSignals(article); assert.ok(signals.some((s) => s.dimensionType === "country" && s.dimensionKey === "vietnam")); const liked = applyFeedback({ dimensionType: "topic", dimensionKey: "vietnam banking", affinityScore: 50, lastSignalAt: MOCK_CORPUS_NOW.toISOString() }, 1, MOCK_CORPUS_NOW); assert.equal(liked.affinityScore, 58); assert.ok(effectiveAffinity(liked, new Date("2027-09-10T08:00:00Z")) < 56); assert.ok(applyFeedback(liked, -2, MOCK_CORPUS_NOW).affinityScore < liked.affinityScore); });

test("Library derives current state once and keeps users isolated", () => { const events = [{ userId: "a", eventType: "like" as const, storyId: "one", createdAt: "2026-01-01" }, { userId: "a", eventType: "unlike" as const, storyId: "one", createdAt: "2026-01-02" }, { userId: "a", eventType: "like" as const, storyId: "two", createdAt: "2026-01-03" }, { userId: "a", eventType: "save" as const, storyId: "two", createdAt: "2026-01-03" }, { userId: "b", eventType: "like" as const, storyId: "other", createdAt: "2026-01-03" }]; assert.deepEqual(deriveLibraryStoryIds(events, "a"), { liked: ["two"], saved: ["two"] }); });
test("open is allowed once per story per Helsinki date", () => { const event = { eventType: "open" as const, storyId: "one", createdAt: "2026-09-10T21:30:00Z" }; assert.equal(helsinkiDateKey(event.createdAt), "2026-09-11"); assert.equal(canRecordStoryOpen([], "one", new Date("2026-09-10T21:31:00Z")), true); assert.equal(canRecordStoryOpen([event], "one", new Date("2026-09-10T22:00:00Z")), false); assert.equal(canRecordStoryOpen([event], "two", new Date("2026-09-10T22:00:00Z")), true); assert.equal(canRecordStoryOpen([event], "one", new Date("2026-09-11T21:01:00Z")), true); });

test("neutral profile produces learnedPreference 50 and signal strengths remain gradual", () => { assert.equal(learnedPreference(article, [], MOCK_CORPUS_NOW), 50); const liked = updateLearnedProfile([], article, "like", MOCK_CORPUS_NOW); const saved = updateLearnedProfile([], article, "save", MOCK_CORPUS_NOW); const opened = updateLearnedProfile([], article, "open", MOCK_CORPUS_NOW); const topic = (profile: typeof liked) => profile.find((item) => item.dimensionType === "topic")!.affinityScore; assert.ok(topic(liked) > topic(saved)); assert.ok(topic(saved) > topic(opened)); assert.ok(topic(opened) > 50); });
test("demo learning is specific, restrained and deterministic", () => { const first = createLearningDemo(); const second = createLearningDemo(); assert.deepEqual(first.affinities, second.affinities); assert.ok(first.learned.banking > first.learned.lifestyle + 4); assert.ok(first.learned.nordicRefinancing > 50); assert.ok(first.learned.tinySeed < 50); assert.ok(first.learned.majorVc > first.learned.tinySeed); const maxMove = Math.max(...first.after.map((story) => Math.abs(story.score.finalScore - first.before.find((old) => old.id === story.id)!.score.finalScore))); assert.ok(maxMove < 5); });
test("topic and sector learn more than source, decay is symmetric, ranking weights remain v1", () => { const profile = updateLearnedProfile([], article, "like", MOCK_CORPUS_NOW); const topic = profile.find((item) => item.dimensionType === "topic")!.affinityScore; const sector = profile.find((item) => item.dimensionType === "sector")!.affinityScore; const source = profile.find((item) => item.dimensionType === "source")!.affinityScore; assert.ok(topic > source); assert.ok(sector > source); const positive = { dimensionType: "topic" as const, dimensionKey: "x", affinityScore: 70, lastSignalAt: MOCK_CORPUS_NOW.toISOString() }; const negative = { ...positive, affinityScore: 30 }; for (const days of [90, 180, 365]) { const now = new Date(MOCK_CORPUS_NOW.getTime() + days * 86_400_000); assert.ok(effectiveAffinity(positive, now) < 70 && effectiveAffinity(positive, now) > 50); assert.ok(effectiveAffinity(negative, now) > 30 && effectiveAffinity(negative, now) < 50); } assert.equal(RANKING_WEIGHTS.portfolioRelevance, .30); assert.equal(RANKING_WEIGHTS.learnedPreference, .18); });
