import type { RankingArticle } from "@/lib/morning-brief/ranking";

/** Synthetic development corpus only. Never import this as a production source. */
export const MOCK_CORPUS_NOW = new Date("2026-09-10T08:00:00.000Z");
type Draft = Omit<RankingArticle, "id" | "publishedAt" | "countries" | "regions" | "categories" | "topics" | "sectors" | "companies" | "sourceCount"> & Partial<Pick<RankingArticle, "countries" | "regions" | "categories" | "topics" | "sectors" | "companies" | "sourceCount">> & { hoursAgo?: number };
const article = (id: string, draft: Draft): RankingArticle => ({ id, publishedAt: new Date(MOCK_CORPUS_NOW.getTime() - (draft.hoursAgo ?? 4) * 3_600_000).toISOString(), countries: [], regions: [], categories: [], topics: [], sectors: [], companies: [], sourceCount: 1, ...draft });
const makeSeries = (prefix: string, rows: Array<Partial<Draft> & Pick<Draft, "title" | "source" | "summary" | "primarySection">>, defaults: Partial<Draft> = {}) => rows.map((row, index) => article(`${prefix}-${index + 1}`, { contentType: "news", significance: 45, consequence: 40, scope: 35, ...defaults, ...row, hoursAgo: row.hoursAgo ?? 4 + index * 2 }));

const vietnam = [
  article("vietnam-bank-credit", { title: "Vietnam bank credit growth broadens as domestic lending recovers", source: "Reuters", contentType: "breaking_news", eventKey: "vietnam-bank-credit-growth", imageUrl: "/morning-brief/mock/vietnam-banking.png", imageAlt: "Synthetic Vietnam banking illustration", imageSource: "Morning Brief mock asset", countries: ["vietnam"], regions: ["asia"], categories: ["vietnam"], topics: ["vietnam banking", "credit growth", "domestic demand"], sectors: ["banking"], summary: "Synthetic market report on lending conditions.", primarySection: "vietnam", significance: 82, consequence: 84, scope: 72, sourceCount: 3, hoursAgo: 2 }),
  article("vietnam-central-bank", { title: "State Bank of Vietnam adjusts liquidity guidance for commercial lenders", source: "Vietnam Business Daily", contentType: "news", countries: ["vietnam"], regions: ["asia"], categories: ["vietnam"], topics: ["state bank of vietnam", "credit growth", "vietnam banking"], sectors: ["banking"], summary: "Synthetic central-bank policy item.", primarySection: "vietnam", significance: 78, consequence: 82, scope: 70, sourceCount: 2, hoursAgo: 5 }),
  article("vietnam-tourism-noise", { title: "Coastal resort opens a new rooftop restaurant in Da Nang", source: "Vietnam Business Daily", contentType: "news", countries: ["vietnam"], regions: ["asia"], categories: ["vietnam"], topics: ["tourism", "restaurant opening", "lifestyle"], sectors: ["consumer"], summary: "Deliberate low-value Vietnam lifestyle noise.", primarySection: "vietnam", significance: 8, consequence: 5, scope: 6, hoursAgo: 1 }),
  ...makeSeries("vietnam", [
    { title: "VN-Index rises as domestic liquidity improves", source: "Reuters", summary: "Synthetic equity-market update.", primarySection: "vietnam", topics: ["vn-index", "market liquidity", "vietnam equities"], countries: ["vietnam"], categories: ["vietnam"], significance: 70, consequence: 68, scope: 62 },
    { title: "Foreign investors return selectively to Vietnamese large caps", source: "Financial Times", summary: "Synthetic foreign-flow analysis.", primarySection: "vietnam", contentType: "analysis", topics: ["foreign investor", "capital flows", "vietnam equities"], countries: ["vietnam"], categories: ["vietnam"], significance: 72, consequence: 70, scope: 65 },
    { title: "Vietnam property transactions show early signs of stabilisation", source: "Vietnam Business Daily", summary: "Synthetic property-cycle report.", primarySection: "vietnam", topics: ["vietnam property", "credit growth"], countries: ["vietnam"], categories: ["vietnam"], sectors: ["property"], significance: 68, consequence: 76, scope: 58 },
    { title: "Infrastructure disbursement supports Vietnam industrial corridors", source: "Reuters", summary: "Synthetic infrastructure report.", primarySection: "vietnam", topics: ["infrastructure", "vietnam industrials"], countries: ["vietnam"], categories: ["vietnam"], sectors: ["industrials"], significance: 62, consequence: 66, scope: 60 },
    { title: "Manufacturing FDI commitments lift Vietnam export outlook", source: "Financial Times", summary: "Synthetic FDI item.", primarySection: "vietnam", contentType: "analysis", topics: ["vietnam fdi", "manufacturing", "exports"], countries: ["vietnam"], categories: ["vietnam"], sectors: ["industrials"], significance: 75, consequence: 72, scope: 68 },
    { title: "Vietnam consumer demand improves ahead of the holiday period", source: "Vietnam Business Daily", summary: "Synthetic domestic-demand report.", primarySection: "vietnam", topics: ["vietnam consumer", "domestic demand"], countries: ["vietnam"], categories: ["vietnam"], sectors: ["consumer"], significance: 52, consequence: 58, scope: 45 },
    { title: "VND trading remains orderly as import demand picks up", source: "Reuters", summary: "Synthetic currency report.", primarySection: "vietnam", topics: ["vietnam currency", "vnd"], countries: ["vietnam"], categories: ["vietnam"], significance: 64, consequence: 62, scope: 55 },
    { title: "Vietnam settlement reforms keep market classification debate active", source: "Financial Times", summary: "Synthetic market-access analysis.", primarySection: "vietnam", contentType: "long_read", topics: ["market classification", "market regulation", "market access"], countries: ["vietnam"], categories: ["vietnam"], significance: 78, consequence: 80, scope: 68, hoursAgo: 34 },
    { title: "Listed Vietnamese lender reports stronger fee income", source: "Vietnam Business Daily", summary: "Synthetic company event.", primarySection: "vietnam", topics: ["vietnam banking", "listed company"], countries: ["vietnam"], categories: ["vietnam"], sectors: ["banking"], significance: 48, consequence: 52, scope: 35 },
    { title: "Vietnam fiscal programme targets household and infrastructure demand", source: "Official Institution", summary: "Synthetic fiscal-policy release.", primarySection: "vietnam", topics: ["vietnam macro", "fiscal policy", "infrastructure"], countries: ["vietnam"], categories: ["vietnam"], significance: 70, consequence: 70, scope: 65 },
    { title: "ASEAN trade talks create incremental opportunity for Vietnam exporters", source: "BBC", summary: "Synthetic regional trade item.", primarySection: "vietnam", topics: ["asean trade", "exports"], countries: ["vietnam"], categories: ["vietnam"], significance: 45, consequence: 48, scope: 55 },
    { title: "China supply-chain shift gives Vietnam suppliers a new opening", source: "The Economist", contentType: "analysis", summary: "Synthetic supply-chain analysis.", primarySection: "vietnam", topics: ["china supply chain", "manufacturing"], countries: ["vietnam"], categories: ["vietnam"], sectors: ["industrials"], significance: 66, consequence: 65, scope: 65, hoursAgo: 40 },
    { title: "Vietnam football club announces a new youth academy", source: "BBC", summary: "Deliberate sports noise.", primarySection: "vietnam", topics: ["sports"], countries: ["vietnam"], categories: ["vietnam"], significance: 7, consequence: 4, scope: 8 },
    { title: "Vietnam travel guide highlights quieter islands", source: "BBC", summary: "Deliberate generic travel noise.", primarySection: "vietnam", topics: ["travel", "tourism"], countries: ["vietnam"], categories: ["vietnam"], significance: 6, consequence: 4, scope: 7 },
    { title: "Vietnam retail group opens suburban flagship store", source: "Vietnam Business Daily", summary: "Synthetic small company item.", primarySection: "vietnam", topics: ["retail"], countries: ["vietnam"], categories: ["vietnam"], sectors: ["consumer"], significance: 20, consequence: 22, scope: 18 },
    { title: "Vietnam ports report steady container volumes", source: "Reuters", summary: "Synthetic trade-indicator update.", primarySection: "vietnam", topics: ["exports", "shipping"], countries: ["vietnam"], categories: ["vietnam"], sectors: ["industrials"], significance: 46, consequence: 45, scope: 42 },
    { title: "Vietnam telecom operator outlines network investment", source: "Vietnam Business Daily", summary: "Synthetic telecom event.", primarySection: "vietnam", topics: ["telecom", "investment"], countries: ["vietnam"], categories: ["vietnam"], sectors: ["telecom"], significance: 34, consequence: 35, scope: 30 },
    { title: "Vietnam long read examines productivity gains from urbanisation", source: "The Economist", contentType: "long_read", summary: "Synthetic long-form development analysis.", primarySection: "vietnam", topics: ["vietnam macro", "consumer", "industrials"], countries: ["vietnam"], categories: ["vietnam"], significance: 63, consequence: 66, scope: 60, hoursAgo: 60 },
    { title: "Vietnam celebrity launches a beverage collaboration", source: "BBC", summary: "Deliberate celebrity noise.", primarySection: "vietnam", topics: ["celebrity", "lifestyle"], countries: ["vietnam"], categories: ["vietnam"], significance: 4, consequence: 3, scope: 5 },
    { title: "Vietnam industrial park occupancy tightens near export hubs", source: "Vietnam Business Daily", summary: "Synthetic industrial property update.", primarySection: "vietnam", topics: ["vietnam industrials", "fdi", "property"], countries: ["vietnam"], categories: ["vietnam"], sectors: ["industrials"], significance: 54, consequence: 60, scope: 48 },
    { title: "Vietnam regulators consult on listed-company disclosure rules", source: "Official Institution", summary: "Synthetic market-regulation item.", primarySection: "vietnam", topics: ["market regulation", "vietnam equities"], countries: ["vietnam"], categories: ["vietnam"], significance: 62, consequence: 67, scope: 54 },
  ]),
];

const emerging = makeSeries("emerging", [
  { title: "Frontier index provider reviews market accessibility criteria", source: "Reuters", summary: "Synthetic classification decision.", primarySection: "emerging_frontier", topics: ["frontier markets", "market classification", "market access"], categories: ["emerging_frontier"], significance: 82, consequence: 80, scope: 75, sourceCount: 3 },
  { title: "Emerging-market capital flows accelerate into local equity funds", source: "Financial Times", contentType: "analysis", summary: "Synthetic flow analysis.", primarySection: "emerging_frontier", topics: ["emerging markets", "capital flows", "local equities"], categories: ["emerging_frontier"], significance: 72, consequence: 72, scope: 75 },
  { title: "Central bank surprise drives a sharp local currency move", source: "Reuters", summary: "Synthetic monetary-policy update.", primarySection: "emerging_frontier", topics: ["emerging markets", "central bank", "local currencies"], categories: ["emerging_frontier"], significance: 74, consequence: 73, scope: 66 },
  { title: "Market infrastructure upgrade reduces foreign-settlement friction", source: "Official Institution", summary: "Synthetic infrastructure update.", primarySection: "emerging_frontier", topics: ["frontier markets", "market access", "foreign investor accessibility"], categories: ["emerging_frontier"], significance: 68, consequence: 75, scope: 57 },
  { title: "Emerging-market long read maps capital-flow cycles", source: "The Economist", contentType: "long_read", summary: "Synthetic long-form macro analysis.", primarySection: "emerging_frontier", topics: ["emerging markets", "capital flows", "local currencies"], categories: ["emerging_frontier"], significance: 68, consequence: 67, scope: 70, hoursAgo: 56 },
  { title: "Regional exchange launches retail investor campaign", source: "Reuters", summary: "Synthetic low-impact market item.", primarySection: "emerging_frontier", topics: ["local equities"], categories: ["emerging_frontier"], significance: 20, consequence: 18, scope: 25 },
  { title: "Frontier market election changes investor access rules", source: "BBC", summary: "Synthetic regulatory event.", primarySection: "emerging_frontier", topics: ["frontier markets", "market access", "political regulation"], categories: ["emerging_frontier"], significance: 75, consequence: 74, scope: 60 },
  { title: "Emerging-market bank earnings beat expectations", source: "Reuters", summary: "Synthetic regional earnings item.", primarySection: "emerging_frontier", topics: ["emerging markets", "banking"], categories: ["emerging_frontier"], significance: 48, consequence: 52, scope: 48 },
  { title: "Country macro release revises growth outlook upward", source: "Official Institution", summary: "Synthetic macro release.", primarySection: "emerging_frontier", topics: ["emerging markets", "macro"], categories: ["emerging_frontier"], significance: 58, consequence: 55, scope: 58 },
  { title: "Foreign ownership limit consultation starts", source: "Official Institution", summary: "Synthetic market-access consultation.", primarySection: "emerging_frontier", topics: ["foreign investor accessibility", "market access"], categories: ["emerging_frontier"], significance: 62, consequence: 70, scope: 50 },
  { title: "Currency hedging costs decline across selected frontier markets", source: "Financial Times", summary: "Synthetic FX update.", primarySection: "emerging_frontier", topics: ["frontier markets", "local currencies"], categories: ["emerging_frontier"], significance: 44, consequence: 48, scope: 50 },
  { title: "Local pension funds raise equity allocation targets", source: "Reuters", summary: "Synthetic local-flow item.", primarySection: "emerging_frontier", topics: ["capital flows", "local equities"], categories: ["emerging_frontier"], significance: 45, consequence: 45, scope: 42 },
  { title: "Index inclusion timetable shifts by one quarter", source: "Reuters", summary: "Synthetic classification timetable.", primarySection: "emerging_frontier", topics: ["index inclusion", "market classification"], categories: ["emerging_frontier"], significance: 60, consequence: 65, scope: 48 },
  { title: "Emerging-market consumer brand expands distribution", source: "BBC", summary: "Synthetic low-priority company item.", primarySection: "emerging_frontier", topics: ["consumer"], categories: ["emerging_frontier"], significance: 18, consequence: 20, scope: 18 },
]);

const europeanHy = makeSeries("european-hy", [
  { title: "European high-yield spreads tighten as refinancing window reopens", source: "Financial Times", contentType: "analysis", summary: "Synthetic direct HY refinancing story.", primarySection: "credit", topics: ["european high yield", "credit spreads", "refinancing"], categories: ["credit"], significance: 80, consequence: 82, scope: 76, sourceCount: 3 },
  { title: "ECB holds rates while signalling caution on inflation", source: "Reuters", summary: "Synthetic ECB decision.", primarySection: "markets", topics: ["ecb", "rates", "funding costs"], categories: ["markets_macro"], significance: 76, consequence: 72, scope: 85 },
  { title: "European issuer launches bond to address 2028 maturity", source: "Reuters", summary: "Synthetic issuance item.", primarySection: "credit", topics: ["bond issuance", "maturity wall", "refinancing"], categories: ["credit"], significance: 65, consequence: 70, scope: 55 },
  { title: "Rating agency downgrades leveraged consumer borrower", source: "Financial Times", summary: "Synthetic ratings event.", primarySection: "credit", topics: ["ratings", "leveraged finance", "distressed"], categories: ["credit"], significance: 66, consequence: 72, scope: 48 },
  { title: "European distressed debt long read examines default cycle", source: "The Economist", contentType: "long_read", summary: "Synthetic structural credit analysis.", primarySection: "credit", topics: ["defaults", "distressed", "european high yield"], categories: ["credit"], significance: 70, consequence: 72, scope: 70, hoursAgo: 60 },
  { title: "Sponsor-backed borrower seeks amendment and extension", source: "Financial Times", summary: "Synthetic A&E event.", primarySection: "credit", topics: ["sponsor-backed", "refinancing", "leveraged finance"], categories: ["credit"], significance: 67, consequence: 70, scope: 54 },
  { title: "Euribor forward curve eases after inflation release", source: "Reuters", summary: "Synthetic causal rate story.", primarySection: "markets", topics: ["euribor", "rates", "funding costs"], categories: ["markets_macro"], significance: 60, consequence: 65, scope: 75 },
  { title: "European HY primary calendar grows modestly", source: "Reuters", summary: "Synthetic calendar update.", primarySection: "credit", topics: ["european high yield", "bond issuance"], categories: ["credit"], significance: 50, consequence: 52, scope: 50 },
  { title: "Restructuring proposal gains creditor support", source: "Financial Times", summary: "Synthetic restructuring item.", primarySection: "credit", topics: ["restructuring", "default"], categories: ["credit"], significance: 64, consequence: 68, scope: 44 },
  { title: "European credit long read compares covenant quality", source: "Financial Times", contentType: "long_read", summary: "Synthetic covenant analysis.", primarySection: "credit", topics: ["european high yield", "leveraged finance", "covenants"], categories: ["credit"], significance: 62, consequence: 62, scope: 58, hoursAgo: 64 },
  { title: "Small consumer issuer receives a rating upgrade", source: "Reuters", summary: "Synthetic low-impact upgrade.", primarySection: "credit", topics: ["ratings"], categories: ["credit"], significance: 25, consequence: 24, scope: 18 },
  { title: "European private debt fund closes a modest add-on vehicle", source: "Financial Times", summary: "Synthetic low-priority fund item.", primarySection: "credit", topics: ["private credit"], categories: ["credit"], significance: 30, consequence: 32, scope: 25 },
]);

const nordicCredit = makeSeries("nordic-credit", [
  { title: "Swedish property issuer secures refinancing ahead of bond maturity", source: "Nordic Credit Monitor", eventKey: "swedish-property-refinancing", summary: "Synthetic direct Nordic HY event.", primarySection: "credit", countries: ["sweden"], topics: ["nordic credit", "swedish property", "refinancing", "bond"], categories: ["credit"], sectors: ["property"], significance: 80, consequence: 84, scope: 65, sourceCount: 2 },
  { title: "Nordic syndicated loan reprices after covenant reset", source: "Nordic Credit Monitor", summary: "Synthetic loan-market event.", primarySection: "credit", countries: ["norway"], topics: ["nordic credit", "syndicated loan", "covenant", "refinancing"], categories: ["credit"], significance: 78, consequence: 80, scope: 60 },
  { title: "Norwegian energy borrower extends debt maturity", source: "Reuters", summary: "Synthetic energy-credit event.", primarySection: "credit", countries: ["norway"], topics: ["norwegian energy", "nordic credit", "maturity extension"], categories: ["credit"], sectors: ["energy"], significance: 68, consequence: 70, scope: 52 },
  { title: "Nordic shipping issuer launches secured financing", source: "Nordic Credit Monitor", summary: "Synthetic shipping credit item.", primarySection: "credit", countries: ["denmark"], topics: ["shipping issuer", "secured loan", "nordic credit"], categories: ["credit"], sectors: ["shipping"], significance: 58, consequence: 62, scope: 44 },
  { title: "Finnish corporate bond issuer agrees covenant amendment", source: "Kauppalehti", summary: "Synthetic Finnish credit event.", primarySection: "credit", countries: ["finland"], topics: ["nordic credit", "covenant", "bond"], categories: ["credit"], significance: 60, consequence: 65, scope: 42 },
  { title: "Nordic high-yield spreads widen after property valuation review", source: "Nordic Credit Monitor", contentType: "analysis", summary: "Synthetic spreads analysis.", primarySection: "credit", countries: ["sweden"], topics: ["nordic credit", "credit spreads", "property valuations"], categories: ["credit"], sectors: ["property"], significance: 72, consequence: 75, scope: 62 },
  { title: "Sponsor-backed Nordic borrower begins refinancing process", source: "Financial Times", summary: "Synthetic overlapping credit event.", primarySection: "credit", countries: ["sweden"], topics: ["nordic refinancing", "sponsor-backed", "leveraged loan", "refinancing"], categories: ["credit"], significance: 77, consequence: 80, scope: 62 },
  { title: "Nordic secured-loan long read reviews amendment trends", source: "Nordic Credit Monitor", contentType: "long_read", summary: "Synthetic structural loan analysis.", primarySection: "credit", topics: ["secured loans", "amendment", "nordic corporate credit"], categories: ["credit"], significance: 65, consequence: 67, scope: 58, hoursAgo: 55 },
  { title: "Danish leveraged borrower receives fresh equity support", source: "Reuters", summary: "Synthetic sponsor event.", primarySection: "credit", countries: ["denmark"], topics: ["nordic credit", "sponsor-backed", "leveraged finance"], categories: ["credit"], significance: 52, consequence: 56, scope: 40 },
  { title: "Nordic issuer defaults on a small unsecured note", source: "Nordic Credit Monitor", summary: "Synthetic default event.", primarySection: "credit", topics: ["nordic credit", "default"], categories: ["credit"], significance: 64, consequence: 70, scope: 40 },
  { title: "Private-credit lender updates collateral policy", source: "Nordic Credit Monitor", summary: "Synthetic loan policy item.", primarySection: "credit", topics: ["private credit", "collateral", "secured loan"], categories: ["credit"], significance: 48, consequence: 52, scope: 35 },
  { title: "Nordic floating-rate debt pricing eases with Euribor", source: "Reuters", summary: "Synthetic causal rates item.", primarySection: "credit", topics: ["euribor", "floating-rate", "nordic credit"], categories: ["credit"], significance: 52, consequence: 58, scope: 55 },
]);

const finland = makeSeries("finland", [
  { title: "Finnish government outlines fiscal package for Parliament", source: "Yle", eventKey: "finnish-fiscal-package", summary: "Synthetic domestic fiscal package.", primarySection: "finland", countries: ["finland"], topics: ["finland politics", "fiscal policy", "public finances"], categories: ["finland_politics"], significance: 80, consequence: 78, scope: 70, sourceCount: 3 },
  { title: "Finnish industrial investment programme receives final approval", source: "Kauppalehti", summary: "Synthetic industrial investment item.", primarySection: "finland", countries: ["finland"], topics: ["finland business", "industrial investment", "exports"], categories: ["finland_business"], sectors: ["industrials"], significance: 72, consequence: 72, scope: 60 },
  { title: "Bank of Finland revises growth outlook", source: "Official Institution", summary: "Synthetic macro forecast.", primarySection: "finland", countries: ["finland"], topics: ["finland economy", "gdp", "inflation"], categories: ["finland_economy"], significance: 68, consequence: 68, scope: 62 },
  { title: "Finnish listed exporter wins a major order", source: "Kauppalehti", summary: "Synthetic listed-company order.", primarySection: "finland", countries: ["finland"], topics: ["finland business", "export order"], categories: ["finland_business"], sectors: ["industrials"], significance: 55, consequence: 58, scope: 40 },
  { title: "Labour-policy negotiations reopen after wage dispute", source: "Yle", summary: "Synthetic labour-policy development.", primarySection: "politics", countries: ["finland"], topics: ["finland politics", "labor policy"], categories: ["finland_politics"], significance: 58, consequence: 60, scope: 55 },
  { title: "Finnish construction restructuring affects regional suppliers", source: "Talouselämä", summary: "Synthetic restructuring item.", primarySection: "finland", countries: ["finland"], topics: ["finland business", "restructuring", "property"], categories: ["finland_business"], sectors: ["property"], significance: 56, consequence: 65, scope: 45 },
  { title: "Consumer confidence improves modestly in Finland", source: "Yle", summary: "Synthetic confidence release.", primarySection: "finland", countries: ["finland"], topics: ["finland economy", "consumer confidence"], categories: ["finland_economy"], significance: 48, consequence: 50, scope: 45 },
  { title: "EU industrial policy package reshapes Finnish investment incentives", source: "Financial Times", contentType: "analysis", summary: "Synthetic EU policy analysis.", primarySection: "finland", countries: ["finland"], topics: ["finland business", "eu policy", "industrials"], categories: ["finland_business"], significance: 70, consequence: 70, scope: 67 },
  { title: "Finnish productivity long read examines skills and capital formation", source: "The Economist", contentType: "long_read", summary: "Synthetic long-form Finland analysis.", primarySection: "finland", countries: ["finland"], topics: ["finland economy", "productivity"], categories: ["finland_economy"], significance: 66, consequence: 65, scope: 62, hoursAgo: 58 },
  { title: "Finnish property transaction volume rises in one city", source: "Kauppalehti", summary: "Synthetic local property item.", primarySection: "finland", countries: ["finland"], topics: ["property"], categories: ["finland_business"], significance: 24, consequence: 25, scope: 20 },
  { title: "Small Finnish consumer brand opens a flagship store", source: "Talouselämä", summary: "Deliberate domestic noise.", primarySection: "finland", countries: ["finland"], topics: ["retail", "lifestyle"], categories: ["finland_business"], significance: 10, consequence: 10, scope: 8 },
  { title: "Finnish unemployment rate surprises modestly lower", source: "Official Institution", summary: "Synthetic labour-market data.", primarySection: "finland", countries: ["finland"], topics: ["finland economy", "unemployment"], categories: ["finland_economy"], significance: 50, consequence: 52, scope: 50 },
  { title: "Finnish security policy review includes economic resilience", source: "Yle", summary: "Synthetic policy review.", primarySection: "politics", countries: ["finland"], topics: ["finland politics", "security policy"], categories: ["finland_politics"], significance: 62, consequence: 60, scope: 55 },
  { title: "Finnish acquisition creates a new Nordic industrial platform", source: "Talouselämä", summary: "Synthetic M&A event.", primarySection: "finland", countries: ["finland"], topics: ["finland business", "acquisition"], categories: ["finland_business"], significance: 53, consequence: 55, scope: 42 },
  { title: "Parliament committee advances tax-administration reform", source: "Yle", summary: "Synthetic legislative update.", primarySection: "politics", countries: ["finland"], topics: ["finland politics", "taxation", "parliament"], categories: ["finland_politics"], significance: 54, consequence: 58, scope: 48 },
]);

const vcPe = makeSeries("vc-pe", [
  { title: "European software company raises a major growth round", source: "Financial Times", summary: "Synthetic significant funding round.", primarySection: "vc_pe", topics: ["venture capital", "funding round"], categories: ["venture_capital"], significance: 75, consequence: 68, scope: 70 },
  { title: "Nordic buyout fund agrees industrial carve-out", source: "Financial Times", eventKey: "nordic-industrial-carve-out", summary: "Synthetic major PE transaction.", primarySection: "vc_pe", topics: ["private equity", "buyout", "carve-out"], categories: ["private_equity"], significance: 78, consequence: 72, scope: 65 },
  { title: "Finnish startup closes a tiny pre-seed round", source: "Talouselämä", summary: "Deliberate tiny funding noise.", primarySection: "vc_pe", countries: ["finland"], topics: ["venture capital", "seed round"], categories: ["venture_capital"], significance: 12, consequence: 10, scope: 8 },
  { title: "European continuation fund targets mature portfolio assets", source: "Financial Times", contentType: "analysis", summary: "Synthetic continuation-fund analysis.", primarySection: "vc_pe", topics: ["private equity", "continuation fund", "secondaries"], categories: ["private_equity"], significance: 65, consequence: 62, scope: 62 },
  { title: "Nordic venture fund closes new industrial technology vehicle", source: "Talouselämä", summary: "Synthetic fund close.", primarySection: "vc_pe", topics: ["venture capital", "fundraising"], categories: ["venture_capital"], significance: 58, consequence: 55, scope: 48 },
  { title: "Private equity exit market improves for European mid-market assets", source: "The Economist", contentType: "long_read", summary: "Synthetic long-form exit analysis.", primarySection: "vc_pe", topics: ["private equity", "exit", "valuations"], categories: ["private_equity"], significance: 70, consequence: 68, scope: 70, hoursAgo: 52 },
  { title: "Sponsor-backed company completes refinancing before sale process", source: "Financial Times", summary: "Synthetic PE-credit overlap.", primarySection: "vc_pe", topics: ["private equity", "sponsor-backed", "refinancing"], categories: ["private_equity"], significance: 67, consequence: 67, scope: 54 },
  { title: "European secondaries transaction sets new valuation benchmark", source: "Financial Times", summary: "Synthetic secondaries event.", primarySection: "vc_pe", topics: ["private equity", "secondaries", "valuations"], categories: ["private_equity"], significance: 62, consequence: 60, scope: 58 },
  { title: "Nordic SaaS startup announces small bridge financing", source: "Talouselämä", summary: "Deliberate small round.", primarySection: "vc_pe", topics: ["venture capital", "seed round"], categories: ["venture_capital"], significance: 15, consequence: 14, scope: 12 },
  { title: "European VC fundraising takes longer but remains selective", source: "The Economist", contentType: "analysis", summary: "Synthetic fundraising analysis.", primarySection: "vc_pe", topics: ["venture capital", "fundraising"], categories: ["venture_capital"], significance: 55, consequence: 55, scope: 60 },
  { title: "Finnish growth company agrees strategic acquisition", source: "Kauppalehti", summary: "Synthetic Finnish exit.", primarySection: "vc_pe", countries: ["finland"], topics: ["venture capital", "exit", "acquisition"], categories: ["venture_capital"], significance: 48, consequence: 50, scope: 40 },
  { title: "Private-credit financing supports European buyout", source: "Financial Times", summary: "Synthetic PE-credit overlap.", primarySection: "vc_pe", topics: ["private equity", "private credit", "buyout"], categories: ["private_equity"], significance: 60, consequence: 62, scope: 55 },
]);

const global = makeSeries("global", [
  { title: "Major geopolitical escalation disrupts critical trade route", source: "Reuters", contentType: "breaking_news", eventKey: "critical-trade-route-escalation", summary: "Synthetic globally critical geopolitical event.", primarySection: "world", topics: ["geopolitics", "trade policy"], categories: ["global_politics"], significance: 100, consequence: 100, scope: 100, sourceCount: 4, hoursAgo: 1 },
  { title: "Coordinated policy response follows severe global financial shock", source: "Reuters", contentType: "breaking_news", summary: "Synthetic globally critical markets event.", primarySection: "markets", topics: ["markets", "global economy", "financial stability"], categories: ["markets_macro"], significance: 100, consequence: 98, scope: 100, sourceCount: 4, hoursAgo: 2 },
  { title: "Federal Reserve signals a slower path for rate cuts", source: "Reuters", summary: "Synthetic Fed decision.", primarySection: "markets", topics: ["fed", "rates", "markets"], categories: ["markets_macro"], significance: 80, consequence: 75, scope: 88 },
  { title: "Oil shock lifts inflation concerns across Europe", source: "BBC", summary: "Synthetic oil-price event.", primarySection: "markets", topics: ["oil", "commodities", "inflation"], categories: ["commodities"], significance: 78, consequence: 76, scope: 80 },
  { title: "Major equity sell-off follows global growth surprise", source: "Reuters", contentType: "breaking_news", summary: "Synthetic equity-market event.", primarySection: "markets", topics: ["markets", "equity sell-off", "global economy"], categories: ["markets_macro"], significance: 82, consequence: 78, scope: 85 },
  { title: "Trade-policy announcement reshapes supply-chain planning", source: "BBC", summary: "Synthetic global trade-policy event.", primarySection: "politics", topics: ["trade policy", "geopolitics", "supply chain"], categories: ["global_politics"], significance: 74, consequence: 72, scope: 75 },
  { title: "European election result changes coalition outlook", source: "BBC", summary: "Synthetic European politics item.", primarySection: "politics", topics: ["global politics", "europe"], categories: ["global_politics"], significance: 70, consequence: 68, scope: 70 },
  { title: "Global manufacturing PMI misses expectations", source: "Reuters", summary: "Synthetic macro release.", primarySection: "markets", topics: ["global economy", "markets"], categories: ["markets_macro"], significance: 62, consequence: 60, scope: 76 },
  { title: "Geopolitical supply chains long read examines strategic risk", source: "The Economist", contentType: "long_read", summary: "Synthetic long-form geopolitical analysis.", primarySection: "worth_reading", topics: ["geopolitics", "supply chain", "world business"], categories: ["global_politics"], significance: 72, consequence: 72, scope: 75, hoursAgo: 54 },
  { title: "World lifestyle festival announces its programme", source: "BBC", summary: "Deliberate generic world noise.", primarySection: "world", topics: ["lifestyle", "travel"], categories: ["global_politics"], significance: 5, consequence: 4, scope: 8 },
  { title: "Commodity shipping costs move modestly higher", source: "Reuters", summary: "Synthetic ordinary market item.", primarySection: "markets", topics: ["commodities", "shipping"], categories: ["commodities"], significance: 35, consequence: 34, scope: 42 },
  { title: "Global technology conference highlights consumer devices", source: "BBC", summary: "Deliberate generic technology noise.", primarySection: "world", topics: ["consumer", "technology"], categories: ["global_politics"], significance: 12, consequence: 10, scope: 15 },
  { title: "International institution updates global growth forecast", source: "Official Institution", summary: "Synthetic official forecast.", primarySection: "markets", topics: ["global economy", "markets"], categories: ["markets_macro"], significance: 68, consequence: 66, scope: 82 },
  { title: "European energy policy debate returns to affordability", source: "BBC", summary: "Synthetic policy item.", primarySection: "politics", topics: ["energy", "europe", "politics"], categories: ["global_politics"], significance: 52, consequence: 54, scope: 58 },
  { title: "Global consumer confidence survey shows modest improvement", source: "Reuters", summary: "Synthetic low-priority macro item.", primarySection: "world", topics: ["consumer", "global economy"], categories: ["markets_macro"], significance: 38, consequence: 36, scope: 54 },
]);

const duplicateEvents: RankingArticle[] = [
  article("dup-vietnam-local", { title: "Commercial-bank lending expands in August", source: "Vietnam Business Daily", contentType: "news", eventKey: "vietnam-bank-credit-growth", countries: ["vietnam"], regions: ["asia"], categories: ["vietnam"], topics: ["vietnam banking", "credit growth"], sectors: ["banking"], summary: "Synthetic local coverage of the same lending event.", primarySection: "vietnam", significance: 78, consequence: 80, scope: 68, hoursAgo: 4 }),
  article("dup-vietnam-ft", { title: "Vietnam lenders accelerate as domestic demand improves", source: "Financial Times", contentType: "analysis", eventKey: "vietnam-bank-credit-growth", countries: ["vietnam"], regions: ["asia"], categories: ["vietnam"], topics: ["vietnam banking", "credit growth", "domestic demand"], sectors: ["banking"], summary: "Synthetic regional analysis of the same lending event.", primarySection: "vietnam", significance: 80, consequence: 82, scope: 70, hoursAgo: 6 }),
  article("dup-finland-kl", { title: "Kauppalehti reviews Finland fiscal package for businesses", source: "Kauppalehti", contentType: "news", eventKey: "finnish-fiscal-package", countries: ["finland"], categories: ["finland_politics"], topics: ["finland politics", "fiscal policy", "public finances"], sectors: ["industrials"], summary: "Synthetic business perspective.", primarySection: "finland", significance: 78, consequence: 77, scope: 69, hoursAgo: 5 }),
  article("dup-finland-te", { title: "Talouselämä analysis explains Finnish fiscal package", source: "Talouselämä", contentType: "analysis", eventKey: "finnish-fiscal-package", countries: ["finland"], categories: ["finland_politics"], topics: ["finland politics", "fiscal policy", "public finances"], summary: "Synthetic domestic analysis.", primarySection: "finland", significance: 77, consequence: 76, scope: 68, hoursAgo: 8 }),
  article("dup-sweden-ft", { title: "FT analysis examines Swedish property refinancing", source: "Financial Times", contentType: "analysis", eventKey: "swedish-property-refinancing", countries: ["sweden"], categories: ["credit"], topics: ["nordic credit", "swedish property", "refinancing", "bond"], sectors: ["property"], summary: "Synthetic credit analysis.", primarySection: "credit", significance: 79, consequence: 83, scope: 64, hoursAgo: 7 }),
  article("dup-global-bbc", { title: "BBC explains disruption on critical trade route", source: "BBC", contentType: "explainer", eventKey: "critical-trade-route-escalation", categories: ["global_politics"], topics: ["geopolitics", "trade policy"], summary: "Synthetic explanatory coverage.", primarySection: "world", significance: 96, consequence: 96, scope: 98, hoursAgo: 5 }),
  article("dup-global-ft", { title: "FT analysis assesses critical trade route escalation", source: "Financial Times", contentType: "analysis", eventKey: "critical-trade-route-escalation", categories: ["global_politics"], topics: ["geopolitics", "trade policy"], summary: "Synthetic strategic analysis.", primarySection: "world", significance: 96, consequence: 97, scope: 98, hoursAgo: 9 }),
  article("dup-pe-reuters", { title: "Reuters reports Nordic industrial carve-out agreement", source: "Reuters", contentType: "news", eventKey: "nordic-industrial-carve-out", categories: ["private_equity"], topics: ["private equity", "buyout", "carve-out"], summary: "Synthetic transaction coverage.", primarySection: "vc_pe", significance: 76, consequence: 71, scope: 64, hoursAgo: 5 }),
  article("dup-fed-ft", { title: "FT analysis follows Federal Reserve rate decision", source: "Financial Times", contentType: "analysis", eventKey: "fed-slower-rate-cuts", categories: ["markets_macro"], topics: ["fed", "rates", "markets"], summary: "Synthetic Fed analysis.", primarySection: "markets", significance: 78, consequence: 74, scope: 86, hoursAgo: 6 }),
  article("dup-fed-bbc", { title: "BBC explains Federal Reserve slower rate path", source: "BBC", contentType: "explainer", eventKey: "fed-slower-rate-cuts", categories: ["markets_macro"], topics: ["fed", "rates", "markets"], summary: "Synthetic rate decision explainer.", primarySection: "markets", significance: 76, consequence: 72, scope: 84, hoursAgo: 9 }),
];
// Event keys on these two first reports make the synthetic multi-source clusters explicit.
for (const articleItem of global) if (articleItem.id === "global-3") articleItem.eventKey = "fed-slower-rate-cuts";
export const MOCK_NEWS_CORPUS: RankingArticle[] = [...vietnam, ...emerging, ...europeanHy, ...nordicCredit, ...finland, ...vcPe, ...global, ...duplicateEvents];
export const MOCK_CORPUS_BY_SECTION = Object.groupBy(MOCK_NEWS_CORPUS, ({ primarySection }) => primarySection);
