import "server-only";
import { requireApprovedUser } from "@/lib/auth/guard";
import type { MorningBriefStory } from "@/components/morning-brief/mock-data";
import { deriveCurrentStoryFeedback } from "./learning";
import { importedArticleIds } from "./library";
import { groupMorningBriefStories } from "./section-view-model";

const tone = (section: string): MorningBriefStory["imageTone"] => section === "vietnam" ? "violet" : section === "credit" ? "green" : section === "finland" ? "blue" : section === "vc_pe" || section === "world" ? "rose" : "sand";
const label = (publishedAt: string) => `${Math.max(0, Math.round((Date.now() - new Date(publishedAt).getTime()) / 3_600_000))}h`;
export async function getMorningBriefForUser() {
  const { user, supabase } = await requireApprovedUser();
  const { data: brief } = await supabase.from("morning_briefs").select("*").eq("user_id", user.id).eq("status", "ready").order("brief_date", { ascending: false }).order("brief_version", { ascending: false }).limit(1).maybeSingle();
  if (!brief) return null;
  const { data: items } = await supabase.from("morning_brief_items").select("*").eq("brief_id", brief.id).order("section").order("rank"); if (!items?.length) return null;
  const ids = [...new Set(items.map((item) => item.story_cluster_id).filter((id): id is string => Boolean(id)))]; const { data: clusters } = await supabase.from("morning_brief_story_clusters").select("*").in("id", ids); const clusterMap = new Map((clusters ?? []).map((cluster) => [cluster.id, cluster]));
  const articleIds = [...new Set((clusters ?? []).map((cluster) => cluster.primary_article_id).filter((id): id is string => Boolean(id)))]; const [{ data: articles }, { data: classifications }, { data: sources }] = await Promise.all([supabase.from("morning_brief_articles").select("*").in("id", articleIds), supabase.from("morning_brief_article_classifications").select("article_id,topics,categories,why_it_matters,summary,classification_version,created_at").in("article_id", articleIds).order("created_at", { ascending: false }), supabase.from("morning_brief_sources").select("id,name")]); const articleMap = new Map((articles ?? []).map((article) => [article.id, article])); const sourceMap = new Map((sources ?? []).map((source) => [source.id, source.name])); const classMap = new Map<string, NonNullable<typeof classifications>[number]>(); for (const classification of classifications ?? []) if (!classMap.has(classification.article_id)) classMap.set(classification.article_id, classification);
  const { data: feedback } = await supabase.from("morning_brief_feedback").select("story_cluster_id,event_type,created_at").eq("user_id", user.id).in("story_cluster_id", ids); const feedbackByStory = new Map<string, Array<{ eventType: "open" | "like" | "save" | "not_relevant" | "show_fewer_like_this" | "unlike" | "unsave"; storyId: string; createdAt: string }>>(); for (const event of feedback ?? []) if (event.story_cluster_id) feedbackByStory.set(event.story_cluster_id, [...(feedbackByStory.get(event.story_cluster_id) ?? []), { eventType: event.event_type as "like", storyId: event.story_cluster_id, createdAt: event.created_at }]);
  const view = (item: typeof items[number]): MorningBriefStory | null => { const cluster = item.story_cluster_id ? clusterMap.get(item.story_cluster_id) : null; const article = cluster?.primary_article_id ? articleMap.get(cluster.primary_article_id) : null; if (!cluster || !article) return null; const source = sourceMap.get(article.source_id) ?? "Development mock"; const classification = classMap.get(article.id); const state = deriveCurrentStoryFeedback(feedbackByStory.get(cluster.id) ?? []); return { id: cluster.id, rank: item.rank, title: cluster.canonical_headline ?? article.title, source, sourceUrl: article.canonical_url, publishedLabel: label(article.published_at), estimatedReadTime: `${Math.max(1, Math.round((article.body_text?.split(/\s+/).length ?? 500) / 220))} min read`, summary: cluster.canonical_summary ?? classification?.summary ?? article.excerpt ?? "", category: item.section, tags: [...(classification?.topics ?? []), ...(classification?.categories ?? [])].slice(0, 5), imageUrl: cluster.display_image_url, imageAlt: cluster.display_image_alt, imageSource: cluster.display_image_source, imageTone: tone(item.section), imageLabel: item.section, briefing: classification ? { paragraphs: [article.excerpt ?? classification.summary ?? ""].filter(Boolean), whyItMatters: classification.why_it_matters ?? "Included because it is relevant to your interests.", keyTakeaways: classification.topics.slice(0, 4), generatedFromArticleIds: [article.id], generationVersion: classification.classification_version } : undefined, liked: state.liked, saved: state.saved, relatedCoverage: [] }; };
  const sections = groupMorningBriefStories(items.map(view).filter((story): story is MorningBriefStory => Boolean(story)));
  return { brief, sections };
}

/** User-scoped detail lookup. The UI fallback briefing stays resilient until richer mock briefings are mapped. */
export async function getMorningBriefStoryForUser(id: string) {
  const [brief, library] = await Promise.all([getMorningBriefForUser(), getMorningBriefLibraryForUser()]);
  const stories = [...(brief ? Object.values(brief.sections).flat() : []), ...library.imported]; const story = stories.find((item) => item.id === id) ?? null;
  return story ? { story, relatedStories: stories.filter((item) => item.id !== id).slice(0, 2) } : null;
}

export async function getMorningBriefLibraryForUser() {
  const [{ user, supabase }, brief] = await Promise.all([requireApprovedUser(), getMorningBriefForUser()]);
  const briefStories = brief ? [...new Map(Object.values(brief.sections).flat().map((story) => [story.id, story])).values()] : [];
  const { data: imports } = await supabase.from("morning_brief_imports").select("linked_article_id,created_at").eq("user_id", user.id).eq("status", "completed").not("linked_article_id", "is", null).order("created_at", { ascending: false });
  const articleIds = importedArticleIds((imports ?? []).map((item) => ({ status: "completed", linkedArticleId: item.linked_article_id })));
  if (!articleIds.length) return { liked: briefStories.filter((story) => story.liked), saved: briefStories.filter((story) => story.saved), imported: [] };
  const [{ data: articles }, { data: links }] = await Promise.all([supabase.from("morning_brief_articles").select("*").in("id", articleIds), supabase.from("morning_brief_cluster_articles").select("cluster_id,article_id").in("article_id", articleIds)]);
  const clusterIds = [...new Set((links ?? []).map((item) => item.cluster_id))];
  const sourceIds = [...new Set((articles ?? []).map((article) => article.source_id))];
  const [{ data: clusters }, { data: sources }, { data: classifications }, { data: feedback }] = await Promise.all([
    supabase.from("morning_brief_story_clusters").select("*").in("id", clusterIds), supabase.from("morning_brief_sources").select("id,name").in("id", sourceIds), supabase.from("morning_brief_article_classifications").select("*").in("article_id", articleIds).order("created_at", { ascending: false }), supabase.from("morning_brief_feedback").select("story_cluster_id,event_type,created_at").eq("user_id", user.id).in("story_cluster_id", clusterIds),
  ]);
  const articleMap = new Map((articles ?? []).map((article) => [article.id, article])); const clusterMap = new Map((clusters ?? []).map((cluster) => [cluster.id, cluster])); const sourceMap = new Map((sources ?? []).map((source) => [source.id, source.name])); const classMap = new Map<string, NonNullable<typeof classifications>[number]>(); for (const item of classifications ?? []) if (!classMap.has(item.article_id)) classMap.set(item.article_id, item);
  const feedbackByStory = new Map<string, Array<{ eventType: "open" | "like" | "save" | "not_relevant" | "show_fewer_like_this" | "unlike" | "unsave"; storyId: string; createdAt: string }>>(); for (const event of feedback ?? []) if (event.story_cluster_id) feedbackByStory.set(event.story_cluster_id, [...(feedbackByStory.get(event.story_cluster_id) ?? []), { eventType: event.event_type as "like", storyId: event.story_cluster_id, createdAt: event.created_at }]);
  const linkByArticle = new Map((links ?? []).map((item) => [item.article_id, item.cluster_id])); const imported = (imports ?? []).map((item, index): MorningBriefStory | null => { const articleId = item.linked_article_id; if (!articleId) return null; const article = articleMap.get(articleId); const clusterId = linkByArticle.get(articleId); const cluster = clusterId ? clusterMap.get(clusterId) : null; if (!article || !cluster) return null; const classification = classMap.get(article.id); const state = deriveCurrentStoryFeedback(feedbackByStory.get(cluster.id) ?? []); const section = classification?.primary_section ?? "world"; return { id: cluster.id, rank: index + 1, title: cluster.canonical_headline ?? article.title, source: sourceMap.get(article.source_id) ?? new URL(article.canonical_url).hostname, sourceUrl: article.canonical_url, publishedLabel: label(article.published_at), estimatedReadTime: `${Math.max(1, Math.round((article.body_text?.split(/\s+/).length ?? 500) / 220))} min read`, summary: cluster.canonical_summary ?? classification?.summary ?? article.excerpt ?? "", category: section, tags: [...(classification?.topics ?? []), ...(classification?.categories ?? [])].slice(0, 5), imageUrl: cluster.display_image_url, imageAlt: cluster.display_image_alt, imageSource: cluster.display_image_source, imageTone: tone(section), imageLabel: section, briefing: classification ? { paragraphs: [article.excerpt ?? classification.summary ?? "", ...(article.body_text ? article.body_text.split(/\n\n+/).filter(Boolean).slice(0, 3) : [])].filter(Boolean), whyItMatters: classification.why_it_matters ?? "Imported because it is relevant to your interests.", keyTakeaways: classification.topics.slice(0, 4), generatedFromArticleIds: [article.id], generationVersion: classification.classification_version } : undefined, liked: state.liked, saved: state.saved, importedAt: new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric", timeZone: "Europe/Helsinki" }).format(new Date(item.created_at)), importStatus: "completed", relatedCoverage: [] }; }).filter((story): story is MorningBriefStory => Boolean(story));
  return { liked: briefStories.filter((story) => story.liked), saved: briefStories.filter((story) => story.saved), imported };
}
