import assert from "node:assert/strict";
import test from "node:test";
import { buildSemanticProfile, cosineSimilarity, likedSimilarityFromProfile, semanticEventsForUser, semanticSeedIntent, semanticSeedWeight } from "./semantic";
import { rankStoriesWithLearnedProfile } from "./learning";
import type { RankedStoryCluster } from "./clustering";

const now = new Date("2026-09-11T09:00:00Z");
test("cosine handles identical and orthogonal vectors", () => { assert.equal(cosineSimilarity([1, 0], [1, 0]), 1); assert.equal(cosineSimilarity([1, 0], [0, 1]), 0); });
test("centroid is deterministic, weights strong import more, and older seeds decay", () => { const imported = buildSemanticProfile([{ storyId: "import", vector: [1, 0], weight: 2, intent: "import", createdAt: now.toISOString() }, { storyId: "save", vector: [0, 1], weight: .25, intent: "save", createdAt: now.toISOString() }])!; assert.ok(imported.vector[0]! > imported.vector[1]!); assert.ok(semanticSeedWeight("like", "2025-09-11T09:00:00Z", now) < semanticSeedWeight("like", now.toISOString(), now)); });
test("no or missing semantic data remains neutral and one seed is damped", () => { assert.equal(likedSimilarityFromProfile(null, [1, 0]).likedSimilarity, 50); const profile = buildSemanticProfile([{ storyId: "a", vector: [1, 0], weight: 1, intent: "like", createdAt: now.toISOString() }])!; assert.equal(likedSimilarityFromProfile(profile, null).likedSimilarity, 50); assert.ok(likedSimilarityFromProfile(profile, [1, 0]).likedSimilarity < 85); const multi = buildSemanticProfile([{ storyId: "a", vector: [1, 0], weight: 1, intent: "like", createdAt: now.toISOString() }, { storyId: "b", vector: [1, 0], weight: 1, intent: "like", createdAt: now.toISOString() }, { storyId: "c", vector: [1, 0], weight: 1, intent: "like", createdAt: now.toISOString() }])!; assert.ok(multi.confidence > profile.confidence); });
test("current feedback state contributes only positive current intent and caps one story at its strongest signal", () => { assert.equal(semanticSeedIntent([{ storyId: "x", eventType: "like", createdAt: now.toISOString() }, { storyId: "x", eventType: "unlike", createdAt: now.toISOString() }]), null); assert.equal(semanticSeedIntent([{ storyId: "x", eventType: "save", createdAt: now.toISOString() }, { storyId: "x", eventType: "unsave", createdAt: now.toISOString() }]), null); assert.equal(semanticSeedIntent([{ storyId: "x", eventType: "import", createdAt: now.toISOString() }, { storyId: "x", eventType: "like", createdAt: now.toISOString() }]), "import"); });
test("semantic seed events remain user-scoped", () => assert.equal(semanticEventsForUser([{ userId: "a", storyId: "a", eventType: "like", createdAt: now.toISOString() }, { userId: "b", storyId: "b", eventType: "import", createdAt: now.toISOString() }], "a").length, 1));
test("fixture semantic specificity distinguishes Nordic credit from Vietnam and lifestyle", () => { const profile = buildSemanticProfile([{ storyId: "seed", vector: [1, .8, 0, 0], weight: 2, intent: "import", createdAt: now.toISOString() }, { storyId: "property", vector: [.9, .7, .1, 0], weight: 1, intent: "like", createdAt: now.toISOString() }])!; const nordic = likedSimilarityFromProfile(profile, [1, .75, .05, 0]).likedSimilarity; const european = likedSimilarityFromProfile(profile, [.6, .7, .2, 0]).likedSimilarity; const vietnam = likedSimilarityFromProfile(profile, [0, .1, 1, .4]).likedSimilarity; const lifestyle = likedSimilarityFromProfile(profile, [0, 0, 0, 1]).likedSimilarity; assert.ok(nordic > european && european > vietnam && vietnam > lifestyle); });

function story(id: string): RankedStoryCluster { const article = { id, title: id, source: "Fixture", publishedAt: now.toISOString(), contentType: "news" as const, countries: [], regions: [], categories: [], topics: [], sectors: [], companies: [], significance: 60, consequence: 60, scope: 60, summary: id, primarySection: "world" as const }; const score = { article, portfolioRelevance: 20, learnedPreference: 50, importanceScore: 50, explicitInterest: 35, freshnessScore: 80, sourceFit: 55, likedSimilarity: 50, noveltyScore: 70, explorationScore: 8, finalScore: 50, mustConsider: false, portfolioMatches: [], reasons: [] }; return { id, primaryArticleId: id, articleIds: [id], headline: id, summary: id, countries: [], categories: [], topics: [], sectors: [], firstPublishedAt: now.toISOString(), latestPublishedAt: now.toISOString(), sourceCount: 1, primarySource: "Fixture", relatedCoverage: [], article, score }; }
test("semantic ranking is deterministic, neutral preserves behavior, and 5% does not overpower strong portfolio relevance", () => { const stories = [story("a"), story("b")]; const neutral = rankStoriesWithLearnedProfile(stories, [], now); const semantic = rankStoriesWithLearnedProfile(stories, [], now, new Map([["a", { likedSimilarity: 90, seedCount: 3, confidence: 1 }], ["b", { likedSimilarity: 20, seedCount: 3, confidence: 1 }]])); assert.equal(neutral[0]!.score.likedSimilarity, 50); assert.ok(semantic[0]!.score.finalScore >= semantic[1]!.score.finalScore); assert.ok(Math.abs(semantic[0]!.score.finalScore - neutral[0]!.score.finalScore) <= 3); });
