import type { MorningBriefContentType, MorningBriefFeedbackType, MorningBriefSection } from "@/lib/morning-brief/taxonomy";

export type NewsSource = { id: string; slug: string; name: string; baseUrl?: string | null; sourceType: "rss" | "api" | "web_metadata" | "manual" | "official" | "other"; defaultLanguage?: string | null; enabled: boolean; defaultContentType?: MorningBriefContentType | null; metadata: Record<string, unknown> };
export type NewsArticle = { id: string; sourceId: string; sourceArticleId?: string | null; title: string; subtitle?: string | null; excerpt?: string | null; bodyText?: string | null; canonicalUrl: string; author?: string | null; publishedAt: string; fetchedAt: string; language?: string | null; contentType: MorningBriefContentType; accessType: "public" | "subscription" | "unknown"; imageUrl?: string | null; imageAlt?: string | null; imageSource?: string | null; contentHash?: string | null };
export type ArticleClassification = { id: string; articleId: string; countries: string[]; regions: string[]; categories: string[]; topics: string[]; sectors: string[]; companies: string[]; people: string[]; assetClasses: string[]; funds: string[]; eventType?: string | null; significance?: number | null; consequence?: number | null; scope?: number | null; confidence?: number | null; primarySection?: MorningBriefSection | null; summary?: string | null; whyItMatters?: string | null; classificationVersion: string };
export type StoryCluster = { id: string; primaryArticleId?: string | null; canonicalHeadline?: string | null; canonicalSummary?: string | null; eventKey?: string | null; displayImageUrl?: string | null; displayImageAlt?: string | null; displayImageSource?: string | null; firstPublishedAt?: string | null; latestPublishedAt?: string | null; sourceCount: number; clusterVersion: string };
export type ClusterArticle = { clusterId: string; articleId: string; relationType: "primary" | "same_event" | "analysis" | "local_perspective" | "follow_up"; similarity?: number | null; sourcePriority?: number | null };
export type StoryBriefing = { paragraphs: string[]; whyItMatters: string; keyTakeaways: string[]; exposurePath?: string[]; evidenceNote?: string; generatedFromArticleIds?: string[]; generatedAt?: string; generationVersion?: string };
export type PortfolioAsset = { id: string; userId: string; name: string; slug: string; assetType: "fund" | "equity" | "bond" | "loan_fund" | "credit_strategy" | "other"; priority: number; active: boolean; metadata: Record<string, unknown> };
export type PortfolioExposure = { id: string; userId: string; portfolioAssetId: string; exposureType: "country" | "company" | "sector" | "asset_class" | "topic" | "region"; exposureKey: string; weight?: number | null; relevanceStrength: number; validFrom?: string | null; validTo?: string | null; metadata: Record<string, unknown> };
export type UserPreference = { id: string; userId: string; dimensionType: "category" | "topic" | "country" | "region" | "sector" | "source" | "content_type"; dimensionKey: string; explicitWeight: number; pinned: boolean; metadata: Record<string, unknown> };
export type ArticleFeedback = { id: string; userId: string; articleId?: string | null; storyClusterId?: string | null; eventType: MorningBriefFeedbackType; signalStrength?: number | null; metadata: Record<string, unknown>; createdAt: string };
export type ImportedArticle = { id: string; userId: string; originalUrl: string; normalizedUrl: string; linkedArticleId?: string | null; status: "pending" | "processing" | "completed" | "failed"; errorMessage?: string | null; importStrength?: number | null };
export type LearnedInterest = { id: string; userId: string; dimensionType: string; dimensionKey: string; affinityScore: number; positiveSignalCount: number; negativeSignalCount: number; lastSignalAt?: string | null; modelVersion: string };
export type ArticleScore = { id: string; userId: string; articleId?: string | null; storyClusterId?: string | null; portfolioRelevance: number; learnedPreference: number; importanceScore: number; explicitInterest: number; freshnessScore: number; sourceFit: number; likedSimilarity: number; noveltyScore: number; explorationScore: number; finalScore: number; algorithmVersion: string; scoreExplanation: Record<string, unknown> };
export type DailyBrief = { id: string; userId: string; briefDate: string; briefVersion: number; generatedAt: string; status: "generating" | "ready" | "failed" | "archived"; summaryText?: string | null; algorithmVersion: string; classificationVersion?: string | null; estimatedReadMinutes?: number | null; metadata: Record<string, unknown> };
export type DailyBriefItem = { id: string; briefId: string; storyClusterId?: string | null; articleId?: string | null; section: MorningBriefSection; rank: number; score?: number | null; scoreExplanation?: Record<string, unknown> | null };
