(() => {
  const KEY = "kidePersonalAssistantAgent";
  function validOrigin(value) { try { const url = new URL(value); if (url.pathname !== "/" || url.search || url.hash) return null; if (url.protocol === "https:" || (url.protocol === "http:" && url.hostname === "localhost")) return url.origin; } catch {} return null; }
  async function connection() { return (await chrome.storage.local.get(KEY))[KEY] ?? null; }
  async function request(path, options = {}) { const value = await connection(); if (!value?.origin || !value?.token) throw new Error("Agent not paired."); const response = await fetch(`${value.origin}${path}`, { ...options, headers: { Authorization: `Bearer ${value.token}`, "Content-Type": "application/json", ...(options.headers ?? {}) } }); if (!response.ok) throw new Error(response.status === 401 ? "Agent authentication failed." : "Agent request failed."); return response.json(); }
  async function pair({ origin, pairingCode, deviceName }) { const normalizedOrigin = validOrigin(origin); if (!normalizedOrigin || !pairingCode?.trim() || !deviceName?.trim()) throw new Error("Enter a valid Personal Assistant URL, pairing code, and device name."); const granted = await chrome.permissions.request({ origins: [`${normalizedOrigin}/*`] }); if (!granted) throw new Error("Permission for this Personal Assistant origin was not granted."); const response = await fetch(`${normalizedOrigin}/api/kide/agent/pair`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pairingCode: pairingCode.trim(), deviceName: deviceName.trim() }) }); const body = await response.json(); if (!response.ok || !body.agentToken) throw new Error(body.error || "Pairing failed."); const value = { origin: normalizedOrigin, token: body.agentToken, deviceId: body.device.id, deviceName: body.device.name }; await chrome.storage.local.set({ [KEY]: value }); return { deviceName: value.deviceName }; }
  async function getWatch() { return request("/api/kide/agent/watch", { method: "GET" }); }
  async function heartbeat() { return request("/api/kide/agent/heartbeat", { method: "POST", body: "{}" }); }
  async function report(payload) { return request("/api/kide/agent/status", { method: "POST", body: JSON.stringify(payload) }); }
  globalThis.KidePersonalAssistantAgent = Object.freeze({ connection, pair, getWatch, heartbeat, report, validOrigin });
})();
