(() => {
  const { parseEventInput, normalizeWhitespace, canCreateReservation, validateAutoWatchConfig } = globalThis.KideChromePoc;
  const eventInput = document.querySelector("#event"); const variantInput = document.querySelector("#variant"); const status = document.querySelector("#status"); const find = document.querySelector("#find"); const arm = document.querySelector("#arm"); const confirm = document.querySelector("#confirm"); const summary = document.querySelector("#summary");
  const agentOrigin = document.querySelector("#agent-origin"); const agentCode = document.querySelector("#agent-code"); const agentName = document.querySelector("#agent-name"); const agentStatus = document.querySelector("#agent-status"); const pairAgentButton = document.querySelector("#pair-agent-button");
  const autoEventInput = document.querySelector("#auto-event"); const autoTargetMode = document.querySelector("#auto-target-mode"); const autoExactVariantInput = document.querySelector("#auto-exact-variant"); const autoExactVariantLabel = document.querySelector("#auto-exact-variant-label"); const maxPriceLabel = document.querySelector("#max-price-label"); const maxPriceInput = document.querySelector("#max-price"); const saleStartInput = document.querySelector("#sale-start"); const timeoutInput = document.querySelector("#timeout"); const startNow = document.querySelector("#start-now"); const autoStatus = document.querySelector("#auto-status"); const preparedSummary = document.querySelector("#prepared-summary"); const prepareAuto = document.querySelector("#prepare-auto"); const disarmAuto = document.querySelector("#disarm-auto"); const autoConfirm = document.querySelector("#auto-confirm"); const autoSummary = document.querySelector("#auto-summary");
  let target = null; let preparedAuto = null;
  async function activeTab() { const [tab] = await chrome.tabs.query({ active: true, currentWindow: true }); return tab; }
  function show(message) { status.textContent = message; } function clearConfirmation() { confirm.hidden = true; arm.disabled = !target; } function formatLocal(timestamp) { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(timestamp)); } function formatCents(cents) { return `${(cents / 100).toFixed(2)} €`; }
  function readTarget() { const event = parseEventInput(eventInput.value); const variantName = normalizeWhitespace(variantInput.value); if (!event || !variantName) { show("Enter a valid Kide event URL/UUID and exact variant name."); return null; } return { ...event, variantName }; }
  async function messageTab(type, payload) { const tab = await activeTab(); if (!tab?.id) throw new Error("No active tab."); return chrome.tabs.sendMessage(tab.id, { type, payload }); }
  async function ensureEvent(nextTarget) { const tab = await activeTab(); if (!tab?.url || parseEventInput(tab.url)?.eventId !== nextTarget.eventId) { await chrome.tabs.update(tab.id, { url: nextTarget.eventUrl }); show("Navigated to the Kide event. Reopen the extension after Kide has rendered."); return false; } return true; }
  async function findTicket() { const nextTarget = readTarget(); if (!nextTarget) return; target = nextTarget; clearConfirmation(); await chrome.storage.local.set({ kideChromePocTarget: target }); if (!await ensureEvent(target)) return; const response = await messageTab("FIND_TICKET", target); show(response.message); arm.disabled = response.state !== "FOUND"; }
  async function armReservation() { if (!target) return; const response = await messageTab("ARM_RESERVATION", target); show(response.message); if (canCreateReservation(response.state)) { summary.textContent = `Event: ${response.eventName}\nVariant: ${response.variantName}`; confirm.hidden = false; arm.disabled = true; } }
  async function createReservation() { if (!target) return; document.querySelector("#create").disabled = true; const response = await messageTab("CREATE_RESERVATION", target); show(response.message); confirm.hidden = true; target = null; arm.disabled = true; }
  function readAutoWatch() { const result = validateAutoWatchConfig({ eventInput: autoEventInput.value, targetMode: autoTargetMode.value, exactVariantName: autoExactVariantInput.value, maxPriceInput: maxPriceInput.value, saleStartInput: saleStartInput.value, startWatchingNow: startNow.checked, timeoutInput: timeoutInput.value, now: Date.now() }); if (!result.ok) { autoStatus.textContent = result.error; return null; } return result.value; }
  async function prepareAutoReservation() { const existing = await messageTab("GET_AUTO_RESERVATION"); if (existing.watch?.armed) { autoStatus.textContent = "DISARM the active watch before editing or arming new criteria."; return; } const watch = readAutoWatch(); if (!watch) return; if (!await ensureEvent(watch)) return; preparedAuto = watch; const targetLabel = watch.targetMode === "first_available_under_price" ? `First available under ${formatCents(watch.maxPriceCents)}` : watch.exactVariantName; preparedSummary.textContent = `Prepared: ${targetLabel}`; autoSummary.textContent = `Event: ${watch.eventId}\nTarget: ${targetLabel}\nSale starts: ${formatLocal(watch.saleStart)} local time\nWatch expires: ${formatLocal(watch.expiresAt)}`; autoConfirm.hidden = false; }
  async function armAutoReservation() { if (!preparedAuto) return; const response = await messageTab("ARM_AUTO_RESERVATION", preparedAuto); autoConfirm.hidden = true; preparedAuto = null; autoStatus.textContent = `${response.state}\n${response.message}`; disarmAuto.hidden = response.state !== "ARMED"; }
  async function disarmAutoReservation() { const response = await messageTab("DISARM_AUTO_RESERVATION"); autoStatus.textContent = `${response.state}\n${response.message}`; disarmAuto.hidden = true; }
  async function restoreAutoStatus() { try { const response = await messageTab("GET_AUTO_RESERVATION"); const watch = response.watch; if (!watch) return; const targetLabel = watch.targetMode === "first_available_under_price" ? `First available under ${formatCents(watch.maxPriceCents)}` : (watch.exactVariantName ?? watch.variantName); autoStatus.textContent = `${watch.status || (watch.armed ? "ARMED" : "NOT ARMED")}\nTarget: ${targetLabel}\nExpires: ${formatLocal(watch.expiresAt)}`; disarmAuto.hidden = !watch.armed; } catch { autoStatus.textContent = "Open a Kide event tab to view auto-reservation status."; } }
  find.addEventListener("click", () => findTicket().catch(() => show("Could not communicate with this Kide tab. Reload it normally and try again."))); arm.addEventListener("click", () => armReservation().catch(() => show("Could not arm this Kide ticket."))); document.querySelector("#cancel").addEventListener("click", () => { clearConfirmation(); show("Reservation cancelled before any Kide UI click."); }); document.querySelector("#create").addEventListener("click", () => createReservation().catch(() => show("The reservation attempt could not be completed.")));
  prepareAuto.addEventListener("click", () => prepareAutoReservation().catch(() => { autoStatus.textContent = "Could not prepare the automatic reservation."; })); document.querySelector("#cancel-auto").addEventListener("click", () => { autoConfirm.hidden = true; preparedAuto = null; }); document.querySelector("#arm-auto").addEventListener("click", () => armAutoReservation().catch(() => { autoStatus.textContent = "Could not arm automatic reservation."; })); disarmAuto.addEventListener("click", () => disarmAutoReservation().catch(() => { autoStatus.textContent = "Could not disarm automatic reservation."; }));
  autoTargetMode.addEventListener("change", () => { const firstAvailable = autoTargetMode.value === "first_available_under_price"; maxPriceLabel.hidden = !firstAvailable; autoExactVariantLabel.hidden = firstAvailable; });
  pairAgentButton.addEventListener("click", () => globalThis.KidePersonalAssistantAgent.pair({ origin: agentOrigin.value, pairingCode: agentCode.value, deviceName: agentName.value }).then((value) => { agentCode.value = ""; agentStatus.textContent = `Paired: ${value.deviceName}`; }).catch((error) => { agentStatus.textContent = error instanceof Error ? error.message : "Pairing failed."; }));
  globalThis.KidePersonalAssistantAgent.connection().then((value) => { if (value) { agentOrigin.value = value.origin; agentName.value = value.deviceName; agentStatus.textContent = `Paired: ${value.deviceName}`; } });
  chrome.storage.local.get("kideChromePocTarget").then(({ kideChromePocTarget }) => { if (!kideChromePocTarget) return; eventInput.value = kideChromePocTarget.eventUrl; variantInput.value = kideChromePocTarget.variantName; }); restoreAutoStatus();
})();
