"use client";

import { useState } from "react";
import { Sparkles } from "lucide-react";
import { useRouter } from "next/navigation";
import { generateMorningBriefDailyIntelligence } from "@/lib/actions/morning-brief";
import type { DailyIntelligence } from "@/lib/morning-brief/daily-intelligence-contract";

export function DailyIntelligenceBrief({ intelligence }: { intelligence: DailyIntelligence | null }) {
  const router = useRouter(); const [running, setRunning] = useState(false); const [error, setError] = useState<string | null>(null);
  const generate = async () => { setRunning(true); setError(null); try { const result = await generateMorningBriefDailyIntelligence(); if (!result.ok) { setError(result.error ?? "Could not generate Daily Intelligence. Please try again."); return; } router.refresh(); } catch { setError("Could not generate Daily Intelligence. Please try again."); } finally { setRunning(false); } };
  return <section aria-labelledby="daily-intelligence-title" className="rounded-xl border border-border-subtle bg-card p-5 shadow-xs sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-accent">Morning Brief</p><h2 id="daily-intelligence-title" className="mt-1 font-serif text-2xl text-text-primary">Daily Intelligence</h2></div><Sparkles className="mt-1 h-5 w-5 text-accent" strokeWidth={1.6} /></div>{intelligence ? <div className="mt-5 space-y-6"><div className="space-y-3">{intelligence.executiveSummary.map((paragraph, index) => <p key={index} className="leading-7 text-text-secondary">{paragraph}</p>)}</div><div className="grid gap-3 sm:grid-cols-3">{intelligence.mainThemes.map((theme) => <article key={theme.title} className="rounded-lg bg-surface-subtle p-4"><h3 className="font-medium text-text-primary">{theme.title}</h3><p className="mt-2 text-sm leading-6 text-text-secondary">{theme.explanation}</p></article>)}</div><div className="border-t border-border-subtle pt-5"><h3 className="font-serif text-xl text-text-primary">Why this matters</h3><div className="mt-3 space-y-3">{intelligence.whyThisMatters.map((paragraph, index) => <p key={index} className="leading-7 text-text-secondary">{paragraph}</p>)}</div></div><div className="border-t border-border-subtle pt-5"><h3 className="font-serif text-xl text-text-primary">Watch next</h3><ol className="mt-3 space-y-2 text-sm leading-6 text-text-secondary">{intelligence.watchNext.map((item, index) => <li key={index} className="flex gap-3"><span className="font-medium text-accent">{index + 1}</span><span>{item}</span></li>)}</ol></div>{intelligence.evidenceNote && <p className="border-t border-border-subtle pt-4 text-xs leading-5 text-text-tertiary">{intelligence.evidenceNote}</p>}</div> : <div className="mt-5"><p className="max-w-2xl leading-7 text-text-secondary">Generate a personalized cross-story synthesis from the current Morning Brief. It is updated only when you explicitly request it.</p><button type="button" onClick={generate} disabled={running} className="mt-4 rounded-full bg-accent px-4 py-2 text-sm font-medium text-white disabled:opacity-60">{running ? "Preparing daily intelligence…" : error ? "Retry Daily Intelligence" : "Generate Daily Intelligence"}</button>{error && <p role="alert" className="mt-3 text-sm text-danger-strong">{error}</p>}</div>}</section>;
}
