import type { StoryBriefing } from "@/lib/morning-brief/types";

// UI mock only.
// In production imageUrl should come from permitted source article metadata
// or another usable article inside the story cluster.

export type BriefCategory = "top5" | "vietnam" | "credit" | "finland" | "markets" | "politics" | "em-frontier" | "vc-pe" | "world";
export type StoryTone = "violet" | "green" | "sand" | "blue" | "rose";
export type CoverageContentType = "news" | "analysis" | "local-perspective";

export type StoryCoverage = { source: string; title: string; contentType: CoverageContentType; publishedLabel: string; url?: string };
export type { StoryBriefing } from "@/lib/morning-brief/types";
export type MorningBriefStory = {
  id: string; rank?: number; title: string; source: string; sourceUrl?: string; publishedLabel: string; estimatedReadTime: string;
  summary: string; category: string; tags: string[];
  /** Resolved by the future clustering layer: primary article image, then same-cluster image, then null for category fallback. */
  imageUrl: string | null; imageAlt?: string | null; imageSource?: string | null; imageTone: StoryTone; imageLabel: string;
  briefing?: StoryBriefing; isNew?: boolean; isUpdated?: boolean; liked?: boolean; saved?: boolean; importedAt?: string; importStatus?: "completed"; relatedCoverage: StoryCoverage[];
};

const mockUrl = (slug: string) => `https://example.com/morning-brief/mock/${slug}`;
const defaultBriefing: StoryBriefing = {
  paragraphs: ["This is a synthetic Morning Brief item used to demonstrate the editorial layout before live source ingestion is available.", "A future source pipeline will provide validated context from the article cluster rather than relying on this mock content."],
  whyItMatters: "This mock story demonstrates how personal relevance will be presented once portfolio and preference data are connected.",
  keyTakeaways: ["Feed summaries and long-form briefings are deliberately separate.", "Original source coverage will remain visible next to the synthesis.", "Image selection is resolved before the UI receives a story."],
};
const makeStory = (story: Omit<MorningBriefStory, "estimatedReadTime" | "relatedCoverage"> & Partial<Pick<MorningBriefStory, "estimatedReadTime" | "relatedCoverage">>): MorningBriefStory => ({ estimatedReadTime: "3 min read", relatedCoverage: [], ...story });

export const categoryTabs: Array<{ id: BriefCategory; label: string; title: string; subtitle: string }> = [
  { id: "top5", label: "Top 5", title: "Top 5 Stories", subtitle: "Your most relevant stories for this morning." },
  { id: "vietnam", label: "Vietnam", title: "Vietnam / PYN Elite", subtitle: "Your key market in focus." },
  { id: "credit", label: "Credit", title: "Credit & High Yield", subtitle: "European HY, Nordic HY and secured lending." },
  { id: "finland", label: "Finland", title: "Finland", subtitle: "Business, economy and policy with real domestic relevance." },
  { id: "markets", label: "Markets", title: "Markets", subtitle: "Rates, equities, commodities and global macro." },
  { id: "politics", label: "Politics", title: "Politics", subtitle: "Policy developments with economic and geopolitical weight." },
  { id: "em-frontier", label: "EM / Frontier", title: "Emerging & Frontier", subtitle: "Country access, capital flows, currencies and local macro." },
  { id: "vc-pe", label: "VC & PE", title: "VC & Private Equity", subtitle: "Meaningful private-market activity across Europe and the Nordics." },
  { id: "world", label: "World", title: "World", subtitle: "The important global developments beyond your personal lenses." },
];

const stories: MorningBriefStory[] = [
  makeStory({ id: "vietnam-credit", rank: 1, title: "Vietnam's banking sector shows stronger credit growth", source: "Reuters", sourceUrl: mockUrl("reuters-vietnam-credit"), publishedLabel: "2h", estimatedReadTime: "4 min read", summary: "Credit growth accelerated as improving domestic demand and property conditions supported lending activity. The trend matters for banks and other businesses tied to Vietnam's domestic cycle.", category: "Vietnam", tags: ["Vietnam", "Banking", "PYN Elite"], imageUrl: "/morning-brief/mock/vietnam-banking.png", imageAlt: "Development mock image of a modern Vietnamese financial district at sunrise", imageSource: "Development mock asset", imageTone: "violet", imageLabel: "Vietnam banking", isNew: true,
    briefing: { paragraphs: ["Synthetic reports in this mock cluster point to firmer credit growth across Vietnam's domestic banking system. Lending activity is portrayed as broadening beyond a narrow set of borrowers as household demand, working-capital needs and selected property transactions improve from a subdued base.", "The relevant context is an uneven recovery after a tighter period for real-estate funding and bond-market confidence. Banks remain central to the adjustment: they are both the main channel for renewed domestic activity and the institutions most exposed if weaker borrowers or developers need further restructuring.", "For investors, a more durable lending pickup could support bank earnings and improve the outlook for consumer-facing companies, construction supply chains and property-linked activity. It would not remove credit-quality risk, but it would make the domestic growth backdrop less dependent on exports alone.", "The next signals to watch are the composition of new lending, funding costs, property transaction volumes and any evidence that non-performing loans are stabilising. Those indicators will help distinguish a broad credit-cycle recovery from a short-lived policy-supported rebound."], whyItMatters: "Vietnamese credit growth is directly relevant through PYN Elite. Stronger lending can influence bank earnings, property activity and domestic consumption, making the credit cycle an important indicator for several areas of the Vietnamese equity market.", keyTakeaways: ["Mock cluster signals portray lending growth as broadening from a low base.", "Banks remain the key transmission channel between policy support and domestic demand.", "Property activity is a useful companion indicator for credit quality and collateral conditions."], generatedFromArticleIds: ["mock-reuters-vietnam-credit", "mock-ft-vietnam-banks", "mock-yle-vietnam"], generationVersion: "ui-mock-v1" },
    relatedCoverage: [{ source: "Financial Times", title: "Mock analysis: Vietnam's domestic credit cycle", contentType: "analysis", publishedLabel: "3h", url: mockUrl("ft-vietnam-credit") }, { source: "Yle", title: "Mock Finnish perspective: Asian market recovery", contentType: "local-perspective", publishedLabel: "4h", url: mockUrl("yle-vietnam-credit") }] }),
  makeStory({ id: "finland-fiscal", rank: 2, title: "Finnish government prepares the next fiscal package", source: "Yle", sourceUrl: mockUrl("yle-finland-fiscal"), publishedLabel: "3h", estimatedReadTime: "4 min read", summary: "Taxation, competitiveness and public finances are returning to the centre of domestic policy discussions. The package's eventual mix will matter for investment and consumer confidence.", category: "Finland", tags: ["Finland", "Politics", "Economy"], imageUrl: "/morning-brief/mock/finland-fiscal.png", imageAlt: "Development mock image of Helsinki civic architecture at dawn", imageSource: "Development mock asset", imageTone: "blue", imageLabel: "Finnish fiscal policy", isNew: true,
    briefing: { paragraphs: ["This synthetic policy cluster describes a Finnish government preparing a fiscal package around public finances, competitiveness and the conditions for private investment. The central political question is not only the package size, but how savings, tax changes and growth measures are balanced.", "Finland enters the discussion with a familiar tension: fiscal consolidation can support confidence in public finances, while businesses and households are watching whether the policy mix also improves incentives to invest, hire and spend. That trade-off makes implementation details more important than the headline figure.", "For the domestic economy, the package could affect demand through household taxes and transfers, while supply-side effects would depend on energy, infrastructure, skills and business taxation measures. Export-oriented companies will assess whether the agenda improves long-term competitiveness rather than just near-term budget arithmetic.", "The next milestones in this mock storyline are cabinet negotiations, published funding assumptions and the parliamentary timetable. Corporate reactions will likely focus on tax treatment, investment incentives and whether the package changes expectations for the medium-term debt path."], whyItMatters: "Fiscal choices shape Finland's domestic investment climate, consumer confidence and business operating environment. The detail of tax and competitiveness measures can matter more than the policy headline for Finnish companies.", keyTakeaways: ["The mock package centres on public finances, competitiveness and investment conditions.", "Tax design and implementation timing are the issues businesses will watch most closely.", "Household-demand effects depend on the balance between savings and tax or transfer measures."], generatedFromArticleIds: ["mock-yle-fiscal", "mock-kl-fiscal", "mock-politico-finland"], generationVersion: "ui-mock-v1" },
    relatedCoverage: [{ source: "Kauppalehti", title: "Mock analysis: investment incentives in the package", contentType: "analysis", publishedLabel: "2h", url: mockUrl("kl-finland-fiscal") }, { source: "Politico Europe", title: "Mock context: Nordic fiscal choices", contentType: "analysis", publishedLabel: "5h", url: mockUrl("politico-finland-fiscal") }] }),
  makeStory({ id: "nordic-refinancing", rank: 3, title: "Nordic companies step up refinancing ahead of the maturity wall", source: "Financial Times", sourceUrl: mockUrl("ft-nordic-refinancing"), publishedLabel: "5h", estimatedReadTime: "4 min read", summary: "Issuers are returning to the market as investors assess refinancing risk, collateral quality and funding costs. The pace of issuance offers a useful read-through on Nordic credit conditions.", category: "Credit", tags: ["Nordic HY", "Refinancing", "Secured Loans"], imageUrl: "/morning-brief/mock/nordic-refinancing.png", imageAlt: "Development mock image of a Nordic business district beside water", imageSource: "Development mock asset", imageTone: "green", imageLabel: "Nordic refinancing",
    briefing: { paragraphs: ["This synthetic credit cluster follows Nordic issuers returning to loan and bond markets ahead of a heavier maturity schedule. The mock reports describe investors differentiating sharply between businesses with resilient cash flow and collateral, and companies whose refinancing case relies on optimistic operating assumptions.", "The context is a market that has reopened selectively after a period of higher rates and more cautious underwriting. Refinancing does not need to be easy to be constructive: a functioning primary market can reduce near-term maturity risk, while the price of access still reveals how lenders assess sector, leverage and documentation quality.", "For high-yield bond and secured-loan holders, new issue terms can provide early evidence of credit discipline. Wider margins, stronger covenants or more collateral protection may improve lender safeguards, but they can also signal that weaker borrowers are paying a material cost to extend maturities.", "Watch the volume of completed deals, the terms offered to investors and the share of borrowers that choose amendments rather than full refinancing. Those developments will help show whether the maturity wall is being managed through healthy access or merely pushed forward."], whyItMatters: "Nordic refinancing conditions are relevant through your Nordic High Yield and Evli Nordic Secured Loan exposure. Pricing, lender protections and maturity extensions all provide information about credit conditions and default risk.", keyTakeaways: ["Mock issuers are portrayed as returning to market before maturities become urgent.", "Collateral quality and recurring cash flow remain key differentiators for lender demand.", "New-issue margins and covenant packages are practical indicators of credit discipline."], generatedFromArticleIds: ["mock-ft-nordic-credit", "mock-reuters-nordic-loans", "mock-creditwire-refinancing"], generationVersion: "ui-mock-v1" },
    relatedCoverage: [{ source: "Reuters", title: "Mock report: Nordic borrowers test new issue demand", contentType: "news", publishedLabel: "4h", url: mockUrl("reuters-nordic-refinancing") }, { source: "European Credit Wire", title: "Mock analysis: covenant and pricing trends", contentType: "analysis", publishedLabel: "6h", url: mockUrl("creditwire-nordic-refinancing") }] }),
  makeStory({ id: "em-flows", rank: 4, title: "Emerging markets attract renewed foreign flows", source: "Bloomberg", sourceUrl: mockUrl("bloomberg-em-flows"), publishedLabel: "6h", summary: "Investors are selectively revisiting local markets where policy credibility and currency stability are improving.", category: "Emerging & Frontier", tags: ["Emerging Markets", "Capital Flows", "Evli Emerging Frontier"], imageUrl: null, imageTone: "sand", imageLabel: "Emerging markets", isUpdated: true }),
  makeStory({ id: "pe-activity", rank: 5, title: "European private-equity activity accelerates around carve-outs", source: "Private Equity International", sourceUrl: mockUrl("pei-carveouts"), publishedLabel: "7h", summary: "Sponsors are focusing on operational value creation as financing discipline remains tighter than in the previous cycle.", category: "VC & Private Equity", tags: ["Private Equity", "Europe", "M&A"], imageUrl: null, imageTone: "rose", imageLabel: "Private markets" }),
  makeStory({ id: "vietnam-reform", title: "Market-access reforms keep Vietnam's classification story in view", source: "Frontier Markets Monitor", sourceUrl: mockUrl("vietnam-reform"), publishedLabel: "1h", summary: "Practical changes in settlement and foreign participation remain closely watched by global investors.", category: "Vietnam", tags: ["Vietnam", "Market Reform", "Foreign Flows"], imageUrl: null, imageTone: "violet", imageLabel: "Vietnam markets" }),
  makeStory({ id: "vietnam-fdi", title: "Manufacturing investment pipeline supports Vietnam's export narrative", source: "Asia Industry Brief", sourceUrl: mockUrl("vietnam-fdi"), publishedLabel: "5h", summary: "New industrial commitments underline the role of FDI and manufacturing in the medium-term growth outlook.", category: "Vietnam", tags: ["Vietnam", "FDI", "Industrials"], imageUrl: null, imageTone: "violet", imageLabel: "Vietnam industry" }),
  makeStory({ id: "vietnam-property", title: "Vietnam property conditions show early signs of stabilisation", source: "Asia Property Review", sourceUrl: mockUrl("vietnam-property"), publishedLabel: "8h", summary: "Financing availability and transaction activity are improving in selected segments of the market.", category: "Vietnam", tags: ["Vietnam", "Property", "Credit"], imageUrl: null, imageTone: "violet", imageLabel: "Vietnam property" }),
  makeStory({ id: "european-loans", title: "European leveraged-loan pricing shifts as rate expectations change", source: "Leveraged Finance Daily", sourceUrl: mockUrl("european-loans"), publishedLabel: "48 min", summary: "New issue discussions reflect a nuanced balance between borrower demand and investor selectivity.", category: "Credit", tags: ["Leveraged Loans", "European Credit", "Rates"], imageUrl: null, imageTone: "green", imageLabel: "European credit", isNew: true }),
  makeStory({ id: "hy-issuance", title: "European high-yield issuance picks up as spreads hold firm", source: "European Credit Wire", sourceUrl: mockUrl("hy-issuance"), publishedLabel: "4h", summary: "Primary-market activity is returning selectively as issuers test demand ahead of upcoming maturities.", category: "Credit", tags: ["European HY", "Issuance", "Credit"], imageUrl: null, imageTone: "green", imageLabel: "High yield" }),
  makeStory({ id: "finland-industry", title: "Industrial investment plans lift attention on Finland's export outlook", source: "Kauppalehti", sourceUrl: mockUrl("finland-industry"), publishedLabel: "1h", summary: "A new investment programme highlights energy availability, industrial competitiveness and jobs.", category: "Finland", tags: ["Finland", "Industry", "Exports"], imageUrl: null, imageTone: "blue", imageLabel: "Finnish industry" }),
  makeStory({ id: "market-rates", title: "Central banks signal patience as markets reset rate-cut expectations", source: "Global Markets Review", sourceUrl: mockUrl("market-rates"), publishedLabel: "1h", summary: "Fresh inflation and activity signals are prompting investors to reassess the timing of monetary easing.", category: "Markets", tags: ["Markets", "Rates", "Macro"], imageUrl: null, imageTone: "sand", imageLabel: "Global markets", isUpdated: true }),
  makeStory({ id: "markets-energy", title: "Oil moves higher as energy-security concerns return to focus", source: "Reuters", sourceUrl: mockUrl("markets-energy"), publishedLabel: "4h", summary: "Commodity markets are balancing supply resilience against a shifting geopolitical backdrop.", category: "Markets", tags: ["Oil", "Commodities", "Geopolitics"], imageUrl: null, imageTone: "sand", imageLabel: "Energy markets" }),
  makeStory({ id: "politics-trade", title: "Trade-policy talks raise questions for global manufacturing supply chains", source: "BBC", sourceUrl: mockUrl("politics-trade"), publishedLabel: "36 min", summary: "Governments are assessing measures that could reshape costs and investment decisions across major trade routes.", category: "Politics", tags: ["Geopolitics", "Trade", "Global Economy"], imageUrl: null, imageTone: "rose", imageLabel: "Global politics", isNew: true }),
  makeStory({ id: "politics-europe", title: "European policy agenda turns toward competitiveness and strategic investment", source: "Politico Europe", sourceUrl: mockUrl("politics-europe"), publishedLabel: "6h", summary: "Industrial capacity, energy and capital-market development are moving to the centre of the debate.", category: "Politics", tags: ["Europe", "Policy", "Competitiveness"], imageUrl: null, imageTone: "rose", imageLabel: "European policy" }),
  makeStory({ id: "em-currency", title: "Currency policy remains a key differentiator across emerging markets", source: "Global FX Note", sourceUrl: mockUrl("em-currency"), publishedLabel: "6h", summary: "Diverging inflation paths keep local rates and currency management central to investor conversations.", category: "Emerging & Frontier", tags: ["Emerging Markets", "FX", "Policy"], imageUrl: null, imageTone: "sand", imageLabel: "Emerging FX" }),
  makeStory({ id: "vc-fund", title: "Nordic venture fund closes a new industrial-technology vehicle", source: "Sifted", sourceUrl: mockUrl("vc-fund"), publishedLabel: "2h", summary: "The fundraise points to continued appetite for specialised strategies despite a selective capital market.", category: "VC & Private Equity", tags: ["VC", "Nordics", "Technology"], imageUrl: null, imageTone: "rose", imageLabel: "Venture capital" }),
  makeStory({ id: "world-energy", title: "Energy-security talks keep commodity risk on the global agenda", source: "International Markets Review", sourceUrl: mockUrl("world-energy"), publishedLabel: "3h", summary: "Officials are balancing supply resilience with affordability as market participants watch the next policy signals.", category: "World", tags: ["World", "Energy", "Commodities"], imageUrl: null, imageTone: "rose", imageLabel: "World affairs" }),
];

const story = (id: string) => stories.find((item) => item.id === id)!;
export const topFive = ["vietnam-credit", "finland-fiscal", "nordic-refinancing", "em-flows", "pe-activity"].map(story);
export const feedByCategory: Record<BriefCategory, MorningBriefStory[]> = { top5: topFive, vietnam: ["vietnam-credit", "vietnam-reform", "vietnam-fdi", "vietnam-property", "em-flows"].map(story), credit: ["nordic-refinancing", "european-loans", "hy-issuance", "market-rates", "vietnam-property"].map(story), finland: ["finland-fiscal", "finland-industry", "politics-europe", "market-rates", "politics-trade"].map(story), markets: ["market-rates", "markets-energy", "em-flows", "european-loans", "vietnam-credit"].map(story), politics: ["politics-trade", "politics-europe", "finland-fiscal", "world-energy", "markets-energy"].map(story), "em-frontier": ["em-flows", "em-currency", "vietnam-reform", "vietnam-fdi", "market-rates"].map(story), "vc-pe": ["pe-activity", "vc-fund", "nordic-refinancing", "finland-industry", "european-loans"].map(story), world: ["politics-trade", "world-energy", "markets-energy", "politics-europe", "market-rates"].map(story) };
export const marketPulse = [{ label: "OMX Helsinki", value: "4,982.1", change: "+1.2%", positive: true }, { label: "VN-Index", value: "1,205.4", change: "+0.8%", positive: true }, { label: "STOXX 600", value: "520.3", change: "+0.4%", positive: true }, { label: "S&P 500", value: "5,472.3", change: "+0.4%", positive: true }];
export const morningSummary = "Vietnam and Nordic credit are among today's most relevant portfolio themes. Global markets are watching rate expectations, while Finnish fiscal policy and European private-market activity remain in focus.";
export function getMockStory(id: string) { return stories.find((item) => item.id === id) ?? null; }
export function getRelatedStories(id: string) { return stories.filter((item) => item.id !== id).slice(0, 2); }
export function getStoryBriefing(storyItem: MorningBriefStory): StoryBriefing { return storyItem.briefing ?? defaultBriefing; }
