// Phase UI mock data only. Replace with persisted Morning Brief stories later.

export type BriefCategory = "top5" | "vietnam" | "credit" | "finland" | "markets" | "politics" | "em-frontier" | "vc-pe" | "world";
export type StoryTone = "violet" | "green" | "sand" | "blue" | "rose";
export type MorningBriefStory = { id: string; title: string; source: string; publishedLabel: string; summary: string; category: string; tags: string[]; imageTone: StoryTone; imageLabel: string; whyItMatters: string; keyTakeaways: string[]; exposurePath: string[]; relatedCoverage: Array<{ source: string; label: string; publishedLabel: string }>; isNew?: boolean; isUpdated?: boolean; readTime?: string };

const makeStory = (story: Omit<MorningBriefStory, "keyTakeaways" | "relatedCoverage" | "readTime"> & Partial<Pick<MorningBriefStory, "keyTakeaways" | "relatedCoverage" | "readTime">>): MorningBriefStory => ({ keyTakeaways: ["The development is material but remains selective.", "Market conditions and policy execution will determine the next move.", "The story has implications beyond its immediate headline."], relatedCoverage: [{ source: "Financial Times", label: "Analysis", publishedLabel: "3h" }, { source: "Reuters", label: "Market update", publishedLabel: "4h" }], readTime: "4 min read", ...story });

export const categoryTabs: Array<{ id: BriefCategory; label: string; title: string; subtitle: string }> = [
  { id: "top5", label: "Top 5", title: "Top 5 Stories", subtitle: "Your most relevant stories for this morning." },
  { id: "vietnam", label: "Vietnam", title: "Vietnam / PYN Elite", subtitle: "Your key market in focus." },
  { id: "credit", label: "Credit", title: "Credit & High Yield", subtitle: "European HY, Nordic HY and secured lending." },
  { id: "finland", label: "Finland", title: "Finland", subtitle: "Business, economy and policy with real domestic relevance." },
  { id: "markets", label: "Markets", title: "Markets", subtitle: "Rates, equities, commodities and global macro." },
  { id: "politics", label: "Politics", title: "Politics", subtitle: "Policy developments with economic and geopolitical weight." },
  { id: "em-frontier", label: "EM / Frontier", title: "Emerging & Frontier", subtitle: "Country access, capital flows, currencies and local macro." },
  { id: "vc-pe", label: "VC / PE", title: "VC & Private Equity", subtitle: "Meaningful private-market activity across Europe and the Nordics." },
  { id: "world", label: "World", title: "World", subtitle: "The important global developments beyond your personal lenses." },
];

const stories: MorningBriefStory[] = [
  makeStory({ id: "vietnam-credit", title: "Vietnam's banking sector shows stronger credit growth", source: "Reuters", publishedLabel: "2h", summary: "Credit growth accelerated as improving domestic demand and property conditions supported lending activity.", category: "Vietnam", tags: ["Vietnam", "Banking", "PYN Elite"], imageTone: "violet", imageLabel: "Vietnam", isNew: true, whyItMatters: "Stronger Vietnamese credit growth may matter through your PYN Elite exposure, particularly banking, property and domestic demand.", exposurePath: ["PYN Elite", "Vietnam", "Banking"] }),
  makeStory({ id: "finland-fiscal", title: "Finnish government prepares the next fiscal package", source: "Yle", publishedLabel: "3h", summary: "Taxation, competitiveness and public finances are returning to the centre of domestic policy discussions.", category: "Finland", tags: ["Finland", "Politics", "Economy"], imageTone: "blue", imageLabel: "Finland", isNew: true, whyItMatters: "Fiscal choices shape Finland's domestic investment climate, consumer confidence and business operating environment.", exposurePath: ["Finland", "Fiscal policy", "Domestic economy"] }),
  makeStory({ id: "nordic-refinancing", title: "Nordic companies step up refinancing ahead of the maturity wall", source: "Financial Times", publishedLabel: "5h", summary: "Issuers are returning to the market as investors assess refinancing risk, collateral quality and funding costs.", category: "Credit", tags: ["Nordic HY", "Refinancing", "Secured Loans"], imageTone: "green", imageLabel: "Credit", whyItMatters: "Nordic refinancing conditions are relevant to your Nordic High Yield and Evli Nordic Secured Loan exposure.", exposurePath: ["Evli Nordic Secured Loan", "Nordic corporate credit", "Refinancing"] }),
  makeStory({ id: "em-flows", title: "Emerging markets attract renewed foreign flows", source: "Bloomberg", publishedLabel: "6h", summary: "Investors are selectively revisiting local markets where policy credibility and currency stability are improving.", category: "Emerging & Frontier", tags: ["Emerging Markets", "Capital Flows", "Evli Emerging Frontier"], imageTone: "sand", imageLabel: "Emerging markets", isUpdated: true, whyItMatters: "Foreign-flow momentum and market accessibility are material inputs for your emerging and frontier-market exposure.", exposurePath: ["Evli Emerging Frontier", "Emerging markets", "Capital flows"] }),
  makeStory({ id: "pe-activity", title: "European private-equity activity accelerates around carve-outs", source: "Private Equity International", publishedLabel: "7h", summary: "Sponsors are focusing on operational value creation as financing discipline remains tighter than in the previous cycle.", category: "VC & Private Equity", tags: ["Private Equity", "Europe", "M&A"], imageTone: "rose", imageLabel: "Private markets", whyItMatters: "The transaction mix offers a read-through on valuations, exit conditions and the role of leverage in European private markets.", exposurePath: ["Private Equity", "Europe", "Transactions"] }),
  makeStory({ id: "vietnam-reform", title: "Market-access reforms keep Vietnam's classification story in view", source: "Frontier Markets Monitor", publishedLabel: "1h", summary: "Practical changes in settlement and foreign participation remain closely watched by global investors.", category: "Vietnam", tags: ["Vietnam", "Market Reform", "Foreign Flows"], imageTone: "violet", imageLabel: "Vietnam markets", whyItMatters: "Market-structure progress could broaden Vietnam's investor base and reshape valuations over time.", exposurePath: ["PYN Elite", "Vietnam equities", "Market regulation"] }),
  makeStory({ id: "vietnam-fdi", title: "Manufacturing investment pipeline supports Vietnam's export narrative", source: "Asia Industry Brief", publishedLabel: "5h", summary: "New industrial commitments underline the role of FDI and manufacturing in the medium-term growth outlook.", category: "Vietnam", tags: ["Vietnam", "FDI", "Industrials"], imageTone: "violet", imageLabel: "Vietnam industry", whyItMatters: "FDI and exports remain important drivers of activity across Vietnam's industrial and consumer economy.", exposurePath: ["PYN Elite", "Vietnam", "Industrials"] }),
  makeStory({ id: "vietnam-property", title: "Vietnam property conditions show early signs of stabilisation", source: "Asia Property Review", publishedLabel: "8h", summary: "Financing availability and transaction activity are improving in selected segments of the market.", category: "Vietnam", tags: ["Vietnam", "Property", "Credit"], imageTone: "violet", imageLabel: "Vietnam property", whyItMatters: "Property conditions influence collateral, consumer confidence and credit growth across the domestic economy.", exposurePath: ["PYN Elite", "Vietnam", "Property"] }),
  makeStory({ id: "european-loans", title: "European leveraged-loan pricing shifts as rate expectations change", source: "Leveraged Finance Daily", publishedLabel: "48 min", summary: "New issue discussions reflect a nuanced balance between borrower demand and investor selectivity.", category: "Credit", tags: ["Leveraged Loans", "European Credit", "Rates"], imageTone: "green", imageLabel: "European credit", isNew: true, whyItMatters: "Loan pricing and issuance conditions are direct signals for the health of secured-credit markets.", exposurePath: ["Evli Nordic Secured Loan", "Leveraged loans", "Rates"] }),
  makeStory({ id: "hy-issuance", title: "European high-yield issuance picks up as spreads hold firm", source: "European Credit Wire", publishedLabel: "4h", summary: "Primary-market activity is returning selectively as issuers test demand ahead of upcoming maturities.", category: "Credit", tags: ["European HY", "Issuance", "Credit"], imageTone: "green", imageLabel: "High yield", whyItMatters: "Issuance volumes and spreads offer a read-through on refinancing access and risk appetite.", exposurePath: ["European High Yield", "Credit spreads", "Issuance"] }),
  makeStory({ id: "finland-industry", title: "Industrial investment plans lift attention on Finland's export outlook", source: "Kauppalehti", publishedLabel: "1h", summary: "A new investment programme highlights energy availability, industrial competitiveness and jobs.", category: "Finland", tags: ["Finland", "Industry", "Exports"], imageTone: "blue", imageLabel: "Finnish industry", whyItMatters: "Large industrial investment can influence growth, supply chains and regional competitiveness.", exposurePath: ["Finland", "Industry", "Exports"] }),
  makeStory({ id: "market-rates", title: "Central banks signal patience as markets reset rate-cut expectations", source: "Global Markets Review", publishedLabel: "1h", summary: "Fresh inflation and activity signals are prompting investors to reassess the timing of monetary easing.", category: "Markets", tags: ["Markets", "Rates", "Macro"], imageTone: "sand", imageLabel: "Global markets", isUpdated: true, whyItMatters: "The rate path shapes equity risk appetite, refinancing costs and credit spreads across your key lenses.", exposurePath: ["European High Yield", "ECB rates", "Funding costs"] }),
  makeStory({ id: "markets-energy", title: "Oil moves higher as energy-security concerns return to focus", source: "Reuters", publishedLabel: "4h", summary: "Commodity markets are balancing supply resilience against a shifting geopolitical backdrop.", category: "Markets", tags: ["Oil", "Commodities", "Geopolitics"], imageTone: "sand", imageLabel: "Energy markets", whyItMatters: "Energy moves can alter inflation expectations, risk sentiment and corporate input costs.", exposurePath: ["Global markets", "Commodities", "Inflation"] }),
  makeStory({ id: "politics-trade", title: "Trade-policy talks raise questions for global manufacturing supply chains", source: "BBC", publishedLabel: "36 min", summary: "Governments are assessing measures that could reshape costs and investment decisions across major trade routes.", category: "Politics", tags: ["Geopolitics", "Trade", "Global Economy"], imageTone: "rose", imageLabel: "Global politics", isNew: true, whyItMatters: "Trade changes can affect inflation, corporate margins and the global growth outlook.", exposurePath: ["Global markets", "Trade", "Economic growth"] }),
  makeStory({ id: "politics-europe", title: "European policy agenda turns toward competitiveness and strategic investment", source: "Politico Europe", publishedLabel: "6h", summary: "Industrial capacity, energy and capital-market development are moving to the centre of the debate.", category: "Politics", tags: ["Europe", "Policy", "Competitiveness"], imageTone: "rose", imageLabel: "European policy", whyItMatters: "European policy choices can shape funding conditions, industrial investment and market access.", exposurePath: ["Europe", "Policy", "Capital markets"] }),
  makeStory({ id: "em-currency", title: "Currency policy remains a key differentiator across emerging markets", source: "Global FX Note", publishedLabel: "6h", summary: "Diverging inflation paths keep local rates and currency management central to investor conversations.", category: "Emerging & Frontier", tags: ["Emerging Markets", "FX", "Policy"], imageTone: "sand", imageLabel: "Emerging FX", whyItMatters: "Currency and policy credibility can materially shape local returns for international investors.", exposurePath: ["Evli Emerging Frontier", "Currencies", "Local macro"] }),
  makeStory({ id: "vc-fund", title: "Nordic venture fund closes a new industrial-technology vehicle", source: "Sifted", publishedLabel: "2h", summary: "The fundraise points to continued appetite for specialised strategies despite a selective capital market.", category: "VC & Private Equity", tags: ["VC", "Nordics", "Technology"], imageTone: "rose", imageLabel: "Venture capital", whyItMatters: "Fundraising conditions offer a signal on risk appetite and innovation financing across the Nordic ecosystem.", exposurePath: ["Venture Capital", "Nordics", "Technology"] }),
  makeStory({ id: "world-energy", title: "Energy-security talks keep commodity risk on the global agenda", source: "International Markets Review", publishedLabel: "3h", summary: "Officials are balancing supply resilience with affordability as market participants watch the next policy signals.", category: "World", tags: ["World", "Energy", "Commodities"], imageTone: "rose", imageLabel: "World affairs", whyItMatters: "Energy shocks can move inflation expectations and market risk sentiment quickly.", exposurePath: ["Global markets", "Energy", "Risk sentiment"] }),
];

const story = (id: string) => stories.find((item) => item.id === id)!;
export const topFive = ["vietnam-credit", "finland-fiscal", "nordic-refinancing", "em-flows", "pe-activity"].map(story);
export const feedByCategory: Record<BriefCategory, MorningBriefStory[]> = { top5: topFive, vietnam: ["vietnam-credit", "vietnam-reform", "vietnam-fdi", "vietnam-property", "em-flows"].map(story), credit: ["nordic-refinancing", "european-loans", "hy-issuance", "market-rates", "vietnam-property"].map(story), finland: ["finland-fiscal", "finland-industry", "politics-europe", "market-rates", "politics-trade"].map(story), markets: ["market-rates", "markets-energy", "em-flows", "european-loans", "vietnam-credit"].map(story), politics: ["politics-trade", "politics-europe", "finland-fiscal", "world-energy", "markets-energy"].map(story), "em-frontier": ["em-flows", "em-currency", "vietnam-reform", "vietnam-fdi", "market-rates"].map(story), "vc-pe": ["pe-activity", "vc-fund", "nordic-refinancing", "finland-industry", "european-loans"].map(story), world: ["politics-trade", "world-energy", "markets-energy", "politics-europe", "market-rates"].map(story) };
export const marketPulse = [{ label: "OMX Helsinki", value: "4,982.1", change: "+1.2%", positive: true }, { label: "VN-Index", value: "1,205.4", change: "+0.8%", positive: true }, { label: "STOXX 600", value: "520.3", change: "+0.4%", positive: true }, { label: "S&P 500", value: "5,472.3", change: "+0.4%", positive: true }];
export const morningSummary = "Vietnam and Nordic credit are among today's most relevant portfolio themes. Global markets are watching rate expectations, while Finnish fiscal policy and European private-market activity remain in focus.";
export function getMockStory(id: string) { return stories.find((item) => item.id === id) ?? null; }
export function getRelatedStories(id: string) { return stories.filter((item) => item.id !== id).slice(0, 2); }
