"use client";
import { FormEvent, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, Plus } from "lucide-react";
import { StoryFeed } from "./StoryFeed";
import type { MorningBriefStory } from "./mock-data";
import { Button } from "@/components/ui/Button";
import { Dialog } from "@/components/ui/Dialog";
import { Input } from "@/components/ui/Input";
import { importMorningBriefArticle } from "@/lib/actions/morning-brief";

type Tab = "liked" | "saved" | "imported";
export function MorningBriefLibrary({ liked, saved, imported }: { liked: MorningBriefStory[]; saved: MorningBriefStory[]; imported: MorningBriefStory[] }) {
  const [tab, setTab] = useState<Tab>("liked"); const [dialogOpen, setDialogOpen] = useState(false); const [url, setUrl] = useState(""); const [message, setMessage] = useState<string | null>(null); const [pending, startTransition] = useTransition(); const router = useRouter(); const stories = tab === "liked" ? liked : tab === "saved" ? saved : imported;
  function submit(event: FormEvent) { event.preventDefault(); setMessage(null); startTransition(async () => { const result = await importMorningBriefArticle(url); if (!result.ok) { setMessage(result.error ?? "Could not import this article."); return; } setMessage(result.duplicate ? "This article is already in your library." : "Article imported."); setUrl(""); router.refresh(); }); }
  return <main className="mx-auto max-w-4xl pb-10"><Link href="/morning-brief" className="inline-flex items-center gap-1 text-sm font-medium no-underline"><ArrowLeft size={16} />Morning Brief</Link><div className="mt-5 flex items-end justify-between gap-4"><div><h1 className="font-serif text-4xl text-text-primary sm:text-5xl">Library</h1><p className="mt-2 text-sm text-text-secondary">Stories you liked, saved or imported.</p></div>{tab === "imported" && <Button onClick={() => { setMessage(null); setDialogOpen(true); }}><Plus size={16} />Import article</Button>}</div><div className="mt-6 flex gap-2 border-b border-border-subtle pb-3">{(["liked", "saved", "imported"] as const).map((item) => <button key={item} onClick={() => setTab(item)} className={`rounded-full px-4 py-2 text-sm font-medium ${tab === item ? "bg-accent text-white" : "text-text-secondary hover:bg-sand-200"}`}>{item[0]!.toUpperCase() + item.slice(1)}</button>)}</div><div className="mt-6">{stories.length ? <StoryFeed category="world" title={tab === "liked" ? "Liked stories" : tab === "saved" ? "Saved stories" : "Imported articles"} subtitle={tab === "imported" ? "Public articles you added to improve Morning Brief recommendations." : ""} stories={stories} /> : <div className="rounded-xl border border-border-subtle p-8 text-center"><h2 className="font-serif text-2xl">No {tab} stories yet.</h2>{tab === "imported" && <p className="mt-2 text-sm text-text-secondary">Import a public article URL to add it to your library.</p>}</div>}</div><Dialog open={dialogOpen} onClose={() => !pending && setDialogOpen(false)} title="Import article" description="Add a public article URL. Morning Brief will extract and classify the available content."><form onSubmit={submit}><label htmlFor="morning-brief-import-url" className="text-sm font-medium text-text-primary">Article URL</label><Input id="morning-brief-import-url" className="mt-2" type="url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://example.com/article" required disabled={pending} />{message && <p role="status" className={`mt-3 text-sm ${message.startsWith("Could") || message.includes("not allowed") || message.includes("supported") ? "text-danger" : "text-text-secondary"}`}>{message}</p>}<div className="mt-6 flex justify-end gap-3"><Button type="button" variant="secondary" onClick={() => setDialogOpen(false)} disabled={pending}>Cancel</Button><Button type="submit" disabled={pending || !url.trim()}>{pending ? "Importing…" : "Import article"}</Button></div></form></Dialog></main>;
}
