import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Badge } from "@/components/ui/Badge";
import { NewSinceDivider } from "@/components/morning-brief/NewSinceDivider";
import { StoryActions } from "@/components/morning-brief/StoryActions";
import { StoryImage } from "@/components/morning-brief/StoryImage";
import type { BriefCategory, MorningBriefStory } from "@/components/morning-brief/mock-data";

function StoryStatus({ story }: { story: MorningBriefStory }) { return <>{story.isNew && <span className="ml-1 text-[10px] font-semibold uppercase tracking-wide text-accent">NEW</span>}{story.isUpdated && <span className="ml-1 text-[10px] font-semibold uppercase tracking-wide text-success-strong">UPDATED</span>}</>; }
function Tags({ tags }: { tags: string[] }) { return <div className="mt-3 flex flex-wrap gap-1.5">{tags.map((tag) => <Badge key={tag} className="px-2 py-0.5 text-[10px] normal-case tracking-normal">{tag}</Badge>)}</div>; }
function FeaturedStory({ story }: { story: MorningBriefStory }) { return <article className="border-b border-border-subtle pb-7"><Link href={`/morning-brief/story/${story.id}`} className="block no-underline"><StoryImage imageUrl={story.imageUrl} imageAlt={story.imageAlt} label={story.imageLabel} tone={story.imageTone} featured /><div className="mt-4 flex items-start gap-3"><span className="font-serif text-4xl leading-none text-accent">1</span><div><p className="text-xs font-medium text-text-tertiary">{story.category}</p><h3 className="mt-1 font-serif text-3xl leading-[1.08] text-text-primary sm:text-4xl">{story.title}</h3></div></div></Link><div className="mt-3 flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-medium text-text-secondary">{story.source} <span aria-hidden>·</span> {story.publishedLabel}<StoryStatus story={story} /></p><p className="mt-2 max-w-2xl text-sm leading-6 text-text-secondary">{story.summary}</p><Tags tags={story.tags} /></div><StoryActions /></div></article>; }
function StoryRow({ story, rank }: { story: MorningBriefStory; rank?: number }) { return <article className="flex gap-3 border-b border-border-subtle py-5 sm:gap-5"><Link href={`/morning-brief/story/${story.id}`} className="shrink-0"><StoryImage imageUrl={story.imageUrl} imageAlt={story.imageAlt} label={story.imageLabel} tone={story.imageTone} /></Link><div className="min-w-0 flex-1"><div className="flex items-start gap-2"><Link href={`/morning-brief/story/${story.id}`} className="min-w-0 flex-1 no-underline"><h3 className="font-serif text-xl leading-snug text-text-primary"><span className="mr-2 text-accent">{rank ?? ""}</span>{story.title}</h3></Link><StoryActions /></div><p className="mt-1 text-xs font-medium text-text-secondary">{story.source} <span aria-hidden>·</span> {story.publishedLabel}<StoryStatus story={story} /></p><p className="mt-2 line-clamp-2 text-sm leading-5 text-text-secondary">{story.summary}</p><Tags tags={story.tags} /></div></article>; }

export function StoryFeed({ category, title, subtitle, stories }: { category: BriefCategory; title: string; subtitle: string; stories: MorningBriefStory[] }) { const isTopFive = category === "top5"; return <section aria-labelledby="brief-feed-title"><div className="mb-2 flex items-end justify-between gap-4"><div><h2 id="brief-feed-title" className="font-serif text-3xl text-text-primary">{title}</h2><p className="mt-1 text-sm text-text-secondary">{subtitle}</p></div>{isTopFive && <span className="inline-flex shrink-0 items-center gap-1 text-sm font-medium text-accent">Show more <ArrowRight size={15} /></span>}</div><div>{isTopFive ? <><FeaturedStory story={stories[0]!} />{stories.slice(1).map((story, index) => <div key={story.id}>{index === 2 && <NewSinceDivider />}<StoryRow story={story} rank={index + 2} /></div>)}</> : stories.map((story, index) => <StoryRow key={story.id} story={story} rank={index + 1} />)}</div>{!isTopFive && <p className="pt-5 text-center text-sm text-text-tertiary">Mock feed — more stories will load here in a later phase.</p>}</section>; }
