"use client";
import { Bookmark, Heart, MoreHorizontal } from "lucide-react";
import { useState, useTransition } from "react";
import { Dialog } from "@/components/ui/Dialog";
import { recordMorningBriefFeedback } from "@/lib/actions/morning-brief";

type Props = { storyId: string; persistable?: boolean; initialLiked?: boolean; initialSaved?: boolean };
export function StoryActions({ storyId, persistable = true, initialLiked = false, initialSaved = false }: Props) {
  const [liked, setLiked] = useState(initialLiked); const [saved, setSaved] = useState(initialSaved); const [menuOpen, setMenuOpen] = useState(false); const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition(); const buttonClass = "grid h-10 w-10 place-items-center rounded-full text-text-secondary transition-colors hover:bg-sand-200 hover:text-text-primary disabled:opacity-50";
  const send = (event: "like" | "unlike" | "save" | "unsave" | "not_relevant" | "show_fewer_like_this", rollback?: () => void) => { if (!persistable) return; startTransition(async () => { const result = await recordMorningBriefFeedback(storyId, event); if (!result.ok) { rollback?.(); setMessage(result.error ?? "Could not save feedback."); } else setMessage(event === "not_relevant" || event === "show_fewer_like_this" ? "Feedback saved" : ""); }); };
  return <div className="relative flex shrink-0 items-center"><button disabled={pending} type="button" className={buttonClass} aria-label={liked ? "Unlike article" : "Like article"} aria-pressed={liked} onClick={() => { const old = liked; setLiked(!old); send(old ? "unlike" : "like", () => setLiked(old)); }}><Heart size={18} className={liked ? "fill-accent text-accent" : ""} /></button><button disabled={pending} type="button" className={buttonClass} aria-label={saved ? "Remove saved article" : "Save article"} aria-pressed={saved} onClick={() => { const old = saved; setSaved(!old); send(old ? "unsave" : "save", () => setSaved(old)); }}><Bookmark size={18} className={saved ? "fill-accent text-accent" : ""} /></button><button type="button" className={buttonClass} aria-label="More article actions" onClick={() => setMenuOpen(true)}><MoreHorizontal size={19} /></button>{message && <span role="status" className="absolute right-0 top-10 whitespace-nowrap text-xs text-text-tertiary">{message}</span>}<Dialog open={menuOpen} onClose={() => setMenuOpen(false)} title="Article options"><div className="divide-y divide-border-subtle">{[["Not relevant", "not_relevant"], ["Show fewer like this", "show_fewer_like_this"]].map(([label, event]) => <button key={label} type="button" className="block w-full py-3 text-left text-sm text-text-primary hover:text-accent" onClick={() => { send(event as "not_relevant" | "show_fewer_like_this"); setMenuOpen(false); }}>{label}</button>)}</div></Dialog></div>;
}
