"use client";

import { useCallback, useEffect, useState } from "react";
import { ExternalLink, Search } from "lucide-react";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Input } from "@/components/ui/Input";
import type { NormalizedBenefit } from "@/lib/benefits/types";

function cta(benefit: NormalizedBenefit) { return benefit.redemptionType === "code" ? "Näytä koodi" : benefit.redemptionType === "instructions" ? "Katso ohje" : benefit.redemptionType === "link" ? "Avaa etu" : "Hyödynnä etu"; }
export function BenefitsSearch() {
  const [query, setQuery] = useState(""); const [results, setResults] = useState<NormalizedBenefit[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [visibleRedemption, setVisibleRedemption] = useState<string | null>(null);
  const load = useCallback(async (value: string) => { setLoading(true); setError(null); try { const response = await fetch(`/api/benefits?q=${encodeURIComponent(value)}`); const body = await response.json(); if (!response.ok || !body.ok) throw new Error(); setResults(body.results); } catch { setError("Etuja ei voitu hakea juuri nyt."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(""); }, [load]);
  return <div className="space-y-5"><form className="flex gap-2" onSubmit={(event) => { event.preventDefault(); void load(query); }}><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Hae etuja, esimerkiksi autonhuolto tai hotellit" /><Button type="submit" disabled={loading}><Search size={16} />Hae</Button></form>{loading ? <Card><p className="text-sm text-text-secondary">Haetaan Member+ -etuja…</p></Card> : error ? <Card><p className="text-sm text-danger-strong">{error}</p><Button className="mt-3" size="sm" variant="secondary" onClick={() => void load(query)}>Yritä uudelleen</Button></Card> : results.length === 0 ? <Card><p className="text-sm text-text-secondary">Ei sopivia etuja. Kokeile toista hakusanaa.</p></Card> : <div className="grid gap-4 md:grid-cols-2">{results.map((benefit) => <Card key={`${benefit.provider}:${benefit.externalId}`}><div className="flex flex-wrap gap-2"><Badge tone="accent">Member+</Badge>{benefit.providerCategory && <Badge>{benefit.providerCategory.replaceAll("-", " ")}</Badge>}{benefit.unionName && <Badge tone="warning">{benefit.unionName}</Badge>}</div><h2 className="mt-3 font-serif text-xl text-text-primary">{benefit.title}</h2>{benefit.heading && <p className="mt-1 font-medium text-accent-active">{benefit.heading}</p>}<p className="mt-3 line-clamp-3 text-sm text-text-secondary">{benefit.benefitText ?? benefit.description}</p>{visibleRedemption === benefit.externalId && benefit.redemptionCode && <p className={`mt-3 rounded bg-sand-200 p-2 text-sm text-text-primary ${benefit.redemptionType === "code" ? "font-mono" : ""}`}>{benefit.redemptionCode}</p>}<div className="mt-4 flex gap-2">{(benefit.redemptionType === "code" || benefit.redemptionType === "instructions") ? <Button size="sm" variant="secondary" onClick={() => setVisibleRedemption(visibleRedemption === benefit.externalId ? null : benefit.externalId)}>{cta(benefit)}</Button> : benefit.redemptionUrl ? <a className="inline-flex h-8 items-center gap-1 rounded-md bg-accent px-3 text-sm font-medium text-accent-foreground" href={benefit.redemptionUrl} target="_blank" rel="noreferrer">{cta(benefit)}<ExternalLink size={14} /></a> : benefit.sourceUrl ? <a className="inline-flex h-8 items-center gap-1 rounded-md border border-border-default px-3 text-sm font-medium text-text-primary" href={benefit.sourceUrl} target="_blank" rel="noreferrer">{cta(benefit)}<ExternalLink size={14} /></a> : null}</div></Card>)}</div>}</div>;
}
