"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { armKideWatch, createKidePairingCode, disarmKideWatch, revokeKideAgent } from "@/lib/actions/kide";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Input } from "@/components/ui/Input";

type Props = { device: { id: string; name: string; last_seen_at: string | null } | null; watch: { id: string; status: string; target_mode: string; exact_variant_name: string | null; max_price_cents: number | null; sale_start_at: string; expires_at: string; selected_variant_name: string | null; selected_price_cents: number | null } | null };
export function KideControlPlane({ device, watch }: Props) {
  const [event, setEvent] = useState(""); const [mode, setMode] = useState<"exact_variant" | "first_available_under_price">("exact_variant"); const [variant, setVariant] = useState(""); const [maxPrice, setMaxPrice] = useState(""); const [saleStartAt, setSaleStartAt] = useState(""); const [timeout, setTimeoutValue] = useState("10"); const [startNow, setStartNow] = useState(false); const [prepared, setPrepared] = useState(false); const [message, setMessage] = useState<string | null>(null); const [pairingCode, setPairingCode] = useState<string | null>(null); const [pending, startTransition] = useTransition(); const router = useRouter(); const active = watch && ["armed", "waiting_for_sale", "waiting_for_variant", "attempting"].includes(watch.status);
  const formatCents = (value: number | null) => value === null ? "" : `${(value / 100).toFixed(2)} €`;
  const prepare = () => { if (!event.trim()) return setMessage("Enter a valid Kide event ID or URL."); if (mode === "exact_variant" && !variant.trim()) return setMessage("Enter an exact ticket name."); if (mode === "first_available_under_price" && !maxPrice.trim()) return setMessage("Enter a valid maximum price."); if (!startNow && !saleStartAt) return setMessage("Choose a sale start time or Start watching now."); if (!Number.isInteger(Number(timeout)) || Number(timeout) < 1 || Number(timeout) > 60) return setMessage("Enter a valid watch timeout."); setMessage(null); setPrepared(true); };
  const arm = () => startTransition(async () => { const value = await armKideWatch({ event, targetMode: mode, exactVariantName: variant, maxPrice, quantity: 1, saleStartAt: startNow ? new Date().toISOString() : new Date(saleStartAt).toISOString(), timeoutMinutes: Number(timeout), startWatchingNow: startNow }); setMessage(value.ok ? "Kide watch armed. Your local Chrome agent will sync it." : value.error); setPrepared(false); if (value.ok) router.refresh(); });
  const pair = () => startTransition(async () => { const value = await createKidePairingCode(); if (value.ok) setPairingCode(value.pairingCode ?? null); else setMessage(value.error); });
  return <div className="space-y-4"><Card><h2 className="font-serif text-xl text-text-primary">Local Chrome agent</h2>{device ? <div className="mt-3 text-sm text-text-secondary"><p>Paired: Yes · {device.name}</p><p>Last seen: {device.last_seen_at ? new Date(device.last_seen_at).toLocaleString() : "Never"}</p><p>{device.last_seen_at && Date.now() - new Date(device.last_seen_at).getTime() <= 45_000 ? "ONLINE" : "OFFLINE"}</p><Button className="mt-3" size="sm" variant="danger" disabled={pending} onClick={() => startTransition(async () => { if (confirm("Revoke this Chrome agent?")) { const value = await revokeKideAgent(device.id); setMessage(value.ok ? "Agent revoked." : value.error); } })}>Revoke agent</Button></div> : <div className="mt-3"><p className="text-sm text-text-secondary">Not paired</p><Button className="mt-3" size="sm" disabled={pending} onClick={pair}>Pair Chrome agent</Button>{pairingCode && <p className="mt-3 rounded-md bg-warning-bg p-3 text-sm text-text-primary">Pairing code (shown once): {pairingCode}</p>}</div>}</Card>
    <Card><h2 className="font-serif text-xl text-text-primary">Kide Auto Reservation</h2>{active ? <div className="mt-3 space-y-2 text-sm text-text-secondary"><p>Status: {watch.status}</p><p>Target: {watch.target_mode === "first_available_under_price" ? `First available under ${formatCents(watch.max_price_cents)}` : watch.exact_variant_name}</p><p>Sale: {new Date(watch.sale_start_at).toLocaleString()}</p><Button variant="danger" disabled={pending} onClick={() => startTransition(async () => { const value = await disarmKideWatch(watch.id); setMessage(value.ok ? "Watch disarmed." : value.error); if (value.ok) router.refresh(); })}>DISARM</Button></div> : <div className="mt-4 space-y-3"><label className="block text-sm text-text-secondary">Event<Input value={event} onChange={(e) => setEvent(e.target.value)} placeholder="Kide event URL or UUID" /></label><label className="block text-sm text-text-secondary">Target mode<select className="mt-1 h-10 w-full rounded-sm border border-border-default bg-canvas px-3 text-sm" value={mode} onChange={(e) => setMode(e.target.value as typeof mode)}><option value="exact_variant">Exact variant</option><option value="first_available_under_price">First available under max price</option></select></label>{mode === "exact_variant" ? <label className="block text-sm text-text-secondary">Exact ticket name<Input value={variant} onChange={(e) => setVariant(e.target.value)} /></label> : <label className="block text-sm text-text-secondary">Maximum price, EUR<Input value={maxPrice} onChange={(e) => setMaxPrice(e.target.value)} placeholder="15.00" /></label>}<label className="block text-sm text-text-secondary">Sale start<Input type="datetime-local" disabled={startNow} value={saleStartAt} onChange={(e) => setSaleStartAt(e.target.value)} /></label><label className="flex gap-2 text-sm text-text-secondary"><input type="checkbox" checked={startNow} onChange={(e) => setStartNow(e.target.checked)} />Start watching now</label><label className="block text-sm text-text-secondary">Watch timeout, minutes<Input type="number" min="1" max="60" value={timeout} onChange={(e) => setTimeoutValue(e.target.value)} /></label>{prepared && <div className="rounded-md bg-warning-bg p-3 text-sm text-text-secondary">When armed, your paired local Chrome agent may automatically create one temporary Kide reservation. Payment will not be made.<div className="mt-3 flex gap-2"><Button variant="secondary" onClick={() => setPrepared(false)}>Cancel</Button><Button disabled={pending} onClick={arm}>ARM AUTO RESERVATION</Button></div></div>}<Button disabled={pending || prepared} onClick={prepare}>PREPARE</Button></div>}{message && <p className="mt-3 text-sm text-text-secondary">{message}</p>}</Card></div>;
}
