import { htmlToPlainText } from "../html.ts";
import type { BenefitProvider, BenefitRedemptionType, NormalizedBenefit } from "../types.ts";

const BASE = "https://webtool.virabeli.fi/api/web/1.0"; const REVALIDATE_SECONDS = 4 * 60 * 60; const LIMIT = 100;
type RawBenefit = { id?: unknown; order?: unknown; type?: unknown; title?: unknown; benefit?: unknown; restrictions?: unknown; url?: unknown; fromdate?: unknown; todate?: unknown };
type RawCampaign = { id?: unknown; title?: unknown; image?: unknown; description?: unknown; benefits?: unknown; fromdate?: unknown; todate?: unknown; categories?: unknown; chainid?: unknown; web?: unknown; mobileonly?: unknown; locations?: unknown };
type Page = { total?: unknown; kampanjat?: unknown };
function text(value: unknown): string | null { return typeof value === "string" && value.trim() ? value.trim() : null; }
function date(value: unknown): string | null { const raw = text(value); return raw && !raw.startsWith("0001-01-01") && Number.isFinite(Date.parse(raw)) ? new Date(raw).toISOString() : null; }
export function parseCityShoppariList(value: unknown): string[] { return Array.isArray(value) ? value.flatMap(parseCityShoppariList) : typeof value === "string" ? value.split(",").map((entry) => entry.trim()).filter(Boolean) : []; }
export function cityShoppariRedemption(type: unknown, url: string | null): BenefitRedemptionType { return String(type).toUpperCase() === "WEB" && url ? "link" : String(type).toUpperCase() === "ONCE" ? "cityshoppari_app" : url ? "link" : "cityshoppari_app"; }
function responseRows(payload: unknown): { total: number; campaigns: RawCampaign[] } { const page = (payload && typeof payload === "object" ? payload : {}) as Page; return { total: typeof page.total === "number" && page.total >= 0 ? page.total : 0, campaigns: Array.isArray(page.kampanjat) ? page.kampanjat as RawCampaign[] : [] }; }
function authHeader(): string | null { const value = process.env.CITYSHOPPARI_API_AUTHORIZATION?.trim(); return value || null; }
async function fetchPage(page: number, fetcher: typeof fetch): Promise<{ total: number; campaigns: RawCampaign[] }> { const authorization = authHeader(); if (!authorization) throw new Error("CityShoppari provider unavailable"); const response = await fetcher(`${BASE}/campaignsf?page=${page}&limit=${LIMIT}`, { headers: { Authorization: authorization }, next: { revalidate: REVALIDATE_SECONDS } }); if (!response.ok) throw new Error(`CityShoppari catalog request failed (${response.status})`); return responseRows(await response.json()); }
export function normalizeCityShoppariCampaign(raw: RawCampaign, categoryNames = new Map<string, string>()): NormalizedBenefit[] {
  const campaignId = typeof raw.id === "number" || typeof raw.id === "string" ? String(raw.id) : null; const merchant = text(raw.title); if (!campaignId || !merchant || !Array.isArray(raw.benefits)) return []; const locations = parseCityShoppariList(raw.locations); const categories = parseCityShoppariList(raw.categories); const category = categories.map((id) => categoryNames.get(id) ?? id).join(", ") || null;
  return raw.benefits.flatMap((entry): NormalizedBenefit[] => { const benefit = entry as RawBenefit; const order = text(benefit.order) ?? text(benefit.id); const title = text(benefit.title); if (!order || !title) return []; const description = htmlToPlainText(benefit.benefit) || htmlToPlainText(raw.description); const restrictions = htmlToPlainText(benefit.restrictions) || null; const redemptionUrl = text(benefit.url); const validFrom = date(benefit.fromdate) ?? date(raw.fromdate); const validUntil = date(benefit.todate) ?? date(raw.todate); const redemptionType = cityShoppariRedemption(benefit.type, redemptionUrl); const sourceUrl = text(raw.web); return [{ provider: "cityshoppari", externalId: `campaign-${campaignId}-benefit-${order}`, title, heading: title, description, providerCategory: category, normalizedCategory: null, offerer: merchant, locations, restrictions, benefitText: null, redemptionType, redemptionCode: redemptionType === "cityshoppari_app" ? "Kertaetu lunastetaan CityShoppari-sovelluksessa." : null, redemptionUrl: redemptionType === "link" ? redemptionUrl : null, sourceUrl, imageUrl: text(raw.image), validFrom, validUntil, unionId: null, unionName: null, isGeneralBenefit: true, isRecommended: false, providerMetadata: { campaignId, chainId: raw.chainid ?? null, mobileOnly: Boolean(raw.mobileonly), cityShoppariType: text(benefit.type), categoryIds: categories }, searchText: [merchant, title, description, restrictions, category, ...locations].filter(Boolean).join(" ").toLocaleLowerCase("fi-FI") }]; });
}
export async function fetchCityShoppariBenefits(fetcher: typeof fetch = fetch): Promise<NormalizedBenefit[]> { const first = await fetchPage(0, fetcher); const pages = Math.min(Math.ceil(first.total / LIMIT), 20); const more = await Promise.all(Array.from({ length: Math.max(0, pages - 1) }, (_value, index) => fetchPage(index + 1, fetcher))); const campaigns = [...first.campaigns, ...more.flatMap((page) => page.campaigns)]; const unique = new Map<string, RawCampaign>(); for (const campaign of campaigns) { const id = typeof campaign.id === "number" || typeof campaign.id === "string" ? String(campaign.id) : null; if (id) unique.set(id, campaign); } return [...unique.values()].flatMap((campaign) => normalizeCityShoppariCampaign(campaign)); }
export const cityShoppariProvider: BenefitProvider = { id: "cityshoppari", listBenefits: () => authHeader() ? fetchCityShoppariBenefits() : Promise.resolve([]) };
