import assert from "node:assert/strict";
import test from "node:test";
import { cityShoppariProvider, cityShoppariRedemption, normalizeCityShoppariCampaign, parseCityShoppariList } from "./cityshoppari.ts";
import { rankBenefits } from "../search.ts";

const autoCenter = { id: 5662, title: "Tampereen AutoCenter", locations: "Tampere", categories: "15,6", fromdate: "2026-06-18", todate: "2026-12-31", benefits: [{ id: "0", order: "1", type: "WEB", title: "200 € lahjakortti", benefit: "Korjaamopalveluihin", restrictions: "Mainitse CityShoppari", url: "https://example.test/one" }, { id: "0", order: "3", type: "WEB", title: "-15 % ensimmÃ¤isestÃ¤ huollosta tai korjauksesta", benefit: "Valtuutettu merkkihuolto", restrictions: "Etu uusille asiakkaille", url: "https://example.test/service" }] };
test("one campaign creates multiple stable benefits", () => { const benefits = normalizeCityShoppariCampaign(autoCenter, new Map([["15", "Auto"], ["6", "Palvelut"]])); assert.equal(benefits.length, 2); assert.equal(benefits[1]!.externalId, "campaign-5662-benefit-3"); assert.equal(benefits[1]!.redemptionType, "link"); assert.deepEqual(benefits[1]!.locations, ["Tampere"]); assert.equal(benefits[1]!.providerCategory, "Auto, Palvelut"); });
test("handles ONCE, locations and active child dates", () => { const benefits = normalizeCityShoppariCampaign({ ...autoCenter, locations: ["Espoo, Helsinki", "Vantaa"], todate: "2027-04-30", benefits: [{ id: "0", order: "1", type: "ONCE", title: "Loistopesu", todate: "2027-04-30" }, { id: "0", order: "2", type: "WEB", title: "Expired", todate: "2020-01-01" }] }); assert.equal(benefits[0]!.redemptionType, "cityshoppari_app"); assert.deepEqual(benefits[0]!.locations, ["Espoo", "Helsinki", "Vantaa"]); assert.equal(rankBenefits(benefits, "loistopesu helsinki", { memberPlusUnionId: null, memberPlusUnionName: null }).length, 1); });
test("missing authorization disables provider and parsing is clean", async () => { const previous = process.env.CITYSHOPPARI_API_AUTHORIZATION; delete process.env.CITYSHOPPARI_API_AUTHORIZATION; assert.deepEqual(await cityShoppariProvider.listBenefits(), []); if (previous) process.env.CITYSHOPPARI_API_AUTHORIZATION = previous; assert.equal(cityShoppariRedemption("ONCE", null), "cityshoppari_app"); assert.deepEqual(parseCityShoppariList("Espoo, Helsinki, , Vantaa"), ["Espoo", "Helsinki", "Vantaa"]); });
